// Generated by https://github.com/juliettef/IconFontCppHeaders script GenerateIconFontCppHeaders.py
// for C and C++
// from codepoints icons.yml
// for use with font fa-light-300.ttf, fa-regular-400.ttf, fa-solid-900.ttf

#pragma once

#define FONT_ICON_FILE_NAME_FAS "fa-solid-900.ttf"

#define ICON_MIN_FA 0xe005
#define ICON_MAX_16_FA 0xf8ff
#define ICON_MAX_FA 0xf8ff

#pragma region ICONs

#define ICON_FA_AD "\xef\x99\x81"	// U+f641
#define ICON_FA_ADDRESS_BOOK "\xef\x8a\xb9"	// U+f2b9
#define ICON_FA_ADDRESS_CARD "\xef\x8a\xbb"	// U+f2bb
#define ICON_FA_ADJUST "\xef\x81\x82"	// U+f042
#define ICON_FA_AIR_FRESHENER "\xef\x97\x90"	// U+f5d0
#define ICON_FA_ALIGN_CENTER "\xef\x80\xb7"	// U+f037
#define ICON_FA_ALIGN_JUSTIFY "\xef\x80\xb9"	// U+f039
#define ICON_FA_ALIGN_LEFT "\xef\x80\xb6"	// U+f036
#define ICON_FA_ALIGN_RIGHT "\xef\x80\xb8"	// U+f038
#define ICON_FA_ALLERGIES "\xef\x91\xa1"	// U+f461
#define ICON_FA_AMBULANCE "\xef\x83\xb9"	// U+f0f9
#define ICON_FA_AMERICAN_SIGN_LANGUAGE_INTERPRETING "\xef\x8a\xa3"	// U+f2a3
#define ICON_FA_ANCHOR "\xef\x84\xbd"	// U+f13d
#define ICON_FA_ANGLE_DOUBLE_DOWN "\xef\x84\x83"	// U+f103
#define ICON_FA_ANGLE_DOUBLE_LEFT "\xef\x84\x80"	// U+f100
#define ICON_FA_ANGLE_DOUBLE_RIGHT "\xef\x84\x81"	// U+f101
#define ICON_FA_ANGLE_DOUBLE_UP "\xef\x84\x82"	// U+f102
#define ICON_FA_ANGLE_DOWN "\xef\x84\x87"	// U+f107
#define ICON_FA_ANGLE_LEFT "\xef\x84\x84"	// U+f104
#define ICON_FA_ANGLE_RIGHT "\xef\x84\x85"	// U+f105
#define ICON_FA_ANGLE_UP "\xef\x84\x86"	// U+f106
#define ICON_FA_ANGRY "\xef\x95\x96"	// U+f556
#define ICON_FA_ANKH "\xef\x99\x84"	// U+f644
#define ICON_FA_APPLE_ALT "\xef\x97\x91"	// U+f5d1
#define ICON_FA_ARCHIVE "\xef\x86\x87"	// U+f187
#define ICON_FA_ARCHWAY "\xef\x95\x97"	// U+f557
#define ICON_FA_ARROW_ALT_CIRCLE_DOWN "\xef\x8d\x98"	// U+f358
#define ICON_FA_ARROW_ALT_CIRCLE_LEFT "\xef\x8d\x99"	// U+f359
#define ICON_FA_ARROW_ALT_CIRCLE_RIGHT "\xef\x8d\x9a"	// U+f35a
#define ICON_FA_ARROW_ALT_CIRCLE_UP "\xef\x8d\x9b"	// U+f35b
#define ICON_FA_ARROW_CIRCLE_DOWN "\xef\x82\xab"	// U+f0ab
#define ICON_FA_ARROW_CIRCLE_LEFT "\xef\x82\xa8"	// U+f0a8
#define ICON_FA_ARROW_CIRCLE_RIGHT "\xef\x82\xa9"	// U+f0a9
#define ICON_FA_ARROW_CIRCLE_UP "\xef\x82\xaa"	// U+f0aa
#define ICON_FA_ARROW_DOWN "\xef\x81\xa3"	// U+f063
#define ICON_FA_ARROW_LEFT "\xef\x81\xa0"	// U+f060
#define ICON_FA_ARROW_RIGHT "\xef\x81\xa1"	// U+f061
#define ICON_FA_ARROW_UP "\xef\x81\xa2"	// U+f062
#define ICON_FA_ARROWS_ALT "\xef\x82\xb2"	// U+f0b2
#define ICON_FA_ARROWS_ALT_H "\xef\x8c\xb7"	// U+f337
#define ICON_FA_ARROWS_ALT_V "\xef\x8c\xb8"	// U+f338
#define ICON_FA_ASSISTIVE_LISTENING_SYSTEMS "\xef\x8a\xa2"	// U+f2a2
#define ICON_FA_ASTERISK "\xef\x81\xa9"	// U+f069
#define ICON_FA_AT "\xef\x87\xba"	// U+f1fa
#define ICON_FA_ATLAS "\xef\x95\x98"	// U+f558
#define ICON_FA_ATOM "\xef\x97\x92"	// U+f5d2
#define ICON_FA_AUDIO_DESCRIPTION "\xef\x8a\x9e"	// U+f29e
#define ICON_FA_AWARD "\xef\x95\x99"	// U+f559
#define ICON_FA_BABY "\xef\x9d\xbc"	// U+f77c
#define ICON_FA_BABY_CARRIAGE "\xef\x9d\xbd"	// U+f77d
#define ICON_FA_BACKSPACE "\xef\x95\x9a"	// U+f55a
#define ICON_FA_BACKWARD "\xef\x81\x8a"	// U+f04a
#define ICON_FA_BACON "\xef\x9f\xa5"	// U+f7e5
#define ICON_FA_BACTERIA "\xee\x81\x99"	// U+e059
#define ICON_FA_BACTERIUM "\xee\x81\x9a"	// U+e05a
#define ICON_FA_BAHAI "\xef\x99\xa6"	// U+f666
#define ICON_FA_BALANCE_SCALE "\xef\x89\x8e"	// U+f24e
#define ICON_FA_BALANCE_SCALE_LEFT "\xef\x94\x95"	// U+f515
#define ICON_FA_BALANCE_SCALE_RIGHT "\xef\x94\x96"	// U+f516
#define ICON_FA_BAN "\xef\x81\x9e"	// U+f05e
#define ICON_FA_BAND_AID "\xef\x91\xa2"	// U+f462
#define ICON_FA_BARCODE "\xef\x80\xaa"	// U+f02a
#define ICON_FA_BARS "\xef\x83\x89"	// U+f0c9
#define ICON_FA_BASEBALL_BALL "\xef\x90\xb3"	// U+f433
#define ICON_FA_BASKETBALL_BALL "\xef\x90\xb4"	// U+f434
#define ICON_FA_BATH "\xef\x8b\x8d"	// U+f2cd
#define ICON_FA_BATTERY_EMPTY "\xef\x89\x84"	// U+f244
#define ICON_FA_BATTERY_FULL "\xef\x89\x80"	// U+f240
#define ICON_FA_BATTERY_HALF "\xef\x89\x82"	// U+f242
#define ICON_FA_BATTERY_QUARTER "\xef\x89\x83"	// U+f243
#define ICON_FA_BATTERY_THREE_QUARTERS "\xef\x89\x81"	// U+f241
#define ICON_FA_BED "\xef\x88\xb6"	// U+f236
#define ICON_FA_BEER "\xef\x83\xbc"	// U+f0fc
#define ICON_FA_BELL "\xef\x83\xb3"	// U+f0f3
#define ICON_FA_BELL_SLASH "\xef\x87\xb6"	// U+f1f6
#define ICON_FA_BEZIER_CURVE "\xef\x95\x9b"	// U+f55b
#define ICON_FA_BIBLE "\xef\x99\x87"	// U+f647
#define ICON_FA_BICYCLE "\xef\x88\x86"	// U+f206
#define ICON_FA_BIKING "\xef\xa1\x8a"	// U+f84a
#define ICON_FA_BINOCULARS "\xef\x87\xa5"	// U+f1e5
#define ICON_FA_BIOHAZARD "\xef\x9e\x80"	// U+f780
#define ICON_FA_BIRTHDAY_CAKE "\xef\x87\xbd"	// U+f1fd
#define ICON_FA_BLENDER "\xef\x94\x97"	// U+f517
#define ICON_FA_BLENDER_PHONE "\xef\x9a\xb6"	// U+f6b6
#define ICON_FA_BLIND "\xef\x8a\x9d"	// U+f29d
#define ICON_FA_BLOG "\xef\x9e\x81"	// U+f781
#define ICON_FA_BOLD "\xef\x80\xb2"	// U+f032
#define ICON_FA_BOLT "\xef\x83\xa7"	// U+f0e7
#define ICON_FA_BOMB "\xef\x87\xa2"	// U+f1e2
#define ICON_FA_BONE "\xef\x97\x97"	// U+f5d7
#define ICON_FA_BONG "\xef\x95\x9c"	// U+f55c
#define ICON_FA_BOOK "\xef\x80\xad"	// U+f02d
#define ICON_FA_BOOK_DEAD "\xef\x9a\xb7"	// U+f6b7
#define ICON_FA_BOOK_MEDICAL "\xef\x9f\xa6"	// U+f7e6
#define ICON_FA_BOOK_OPEN "\xef\x94\x98"	// U+f518
#define ICON_FA_BOOK_READER "\xef\x97\x9a"	// U+f5da
#define ICON_FA_BOOKMARK "\xef\x80\xae"	// U+f02e
#define ICON_FA_BORDER_ALL "\xef\xa1\x8c"	// U+f84c
#define ICON_FA_BORDER_NONE "\xef\xa1\x90"	// U+f850
#define ICON_FA_BORDER_STYLE "\xef\xa1\x93"	// U+f853
#define ICON_FA_BOWLING_BALL "\xef\x90\xb6"	// U+f436
#define ICON_FA_BOX "\xef\x91\xa6"	// U+f466
#define ICON_FA_BOX_OPEN "\xef\x92\x9e"	// U+f49e
#define ICON_FA_BOX_TISSUE "\xee\x81\x9b"	// U+e05b
#define ICON_FA_BOXES "\xef\x91\xa8"	// U+f468
#define ICON_FA_BRAILLE "\xef\x8a\xa1"	// U+f2a1
#define ICON_FA_BRAIN "\xef\x97\x9c"	// U+f5dc
#define ICON_FA_BREAD_SLICE "\xef\x9f\xac"	// U+f7ec
#define ICON_FA_BRIEFCASE "\xef\x82\xb1"	// U+f0b1
#define ICON_FA_BRIEFCASE_MEDICAL "\xef\x91\xa9"	// U+f469
#define ICON_FA_BROADCAST_TOWER "\xef\x94\x99"	// U+f519
#define ICON_FA_BROOM "\xef\x94\x9a"	// U+f51a
#define ICON_FA_BRUSH "\xef\x95\x9d"	// U+f55d
#define ICON_FA_BUG "\xef\x86\x88"	// U+f188
#define ICON_FA_BUILDING "\xef\x86\xad"	// U+f1ad
#define ICON_FA_BULLHORN "\xef\x82\xa1"	// U+f0a1
#define ICON_FA_BULLSEYE "\xef\x85\x80"	// U+f140
#define ICON_FA_BURN "\xef\x91\xaa"	// U+f46a
#define ICON_FA_BUS "\xef\x88\x87"	// U+f207
#define ICON_FA_BUS_ALT "\xef\x95\x9e"	// U+f55e
#define ICON_FA_BUSINESS_TIME "\xef\x99\x8a"	// U+f64a
#define ICON_FA_CALCULATOR "\xef\x87\xac"	// U+f1ec
#define ICON_FA_CALENDAR "\xef\x84\xb3"	// U+f133
#define ICON_FA_CALENDAR_ALT "\xef\x81\xb3"	// U+f073
#define ICON_FA_CALENDAR_CHECK "\xef\x89\xb4"	// U+f274
#define ICON_FA_CALENDAR_DAY "\xef\x9e\x83"	// U+f783
#define ICON_FA_CALENDAR_MINUS "\xef\x89\xb2"	// U+f272
#define ICON_FA_CALENDAR_PLUS "\xef\x89\xb1"	// U+f271
#define ICON_FA_CALENDAR_TIMES "\xef\x89\xb3"	// U+f273
#define ICON_FA_CALENDAR_WEEK "\xef\x9e\x84"	// U+f784
#define ICON_FA_CAMERA "\xef\x80\xb0"	// U+f030
#define ICON_FA_CAMERA_RETRO "\xef\x82\x83"	// U+f083
#define ICON_FA_CAMPGROUND "\xef\x9a\xbb"	// U+f6bb
#define ICON_FA_CANDY_CANE "\xef\x9e\x86"	// U+f786
#define ICON_FA_CANNABIS "\xef\x95\x9f"	// U+f55f
#define ICON_FA_CAPSULES "\xef\x91\xab"	// U+f46b
#define ICON_FA_CAR "\xef\x86\xb9"	// U+f1b9
#define ICON_FA_CAR_ALT "\xef\x97\x9e"	// U+f5de
#define ICON_FA_CAR_BATTERY "\xef\x97\x9f"	// U+f5df
#define ICON_FA_CAR_CRASH "\xef\x97\xa1"	// U+f5e1
#define ICON_FA_CAR_SIDE "\xef\x97\xa4"	// U+f5e4
#define ICON_FA_CARAVAN "\xef\xa3\xbf"	// U+f8ff
#define ICON_FA_CARET_DOWN "\xef\x83\x97"	// U+f0d7
#define ICON_FA_CARET_LEFT "\xef\x83\x99"	// U+f0d9
#define ICON_FA_CARET_RIGHT "\xef\x83\x9a"	// U+f0da
#define ICON_FA_CARET_SQUARE_DOWN "\xef\x85\x90"	// U+f150
#define ICON_FA_CARET_SQUARE_LEFT "\xef\x86\x91"	// U+f191
#define ICON_FA_CARET_SQUARE_RIGHT "\xef\x85\x92"	// U+f152
#define ICON_FA_CARET_SQUARE_UP "\xef\x85\x91"	// U+f151
#define ICON_FA_CARET_UP "\xef\x83\x98"	// U+f0d8
#define ICON_FA_CARROT "\xef\x9e\x87"	// U+f787
#define ICON_FA_CART_ARROW_DOWN "\xef\x88\x98"	// U+f218
#define ICON_FA_CART_PLUS "\xef\x88\x97"	// U+f217
#define ICON_FA_CASH_REGISTER "\xef\x9e\x88"	// U+f788
#define ICON_FA_CAT "\xef\x9a\xbe"	// U+f6be
#define ICON_FA_CERTIFICATE "\xef\x82\xa3"	// U+f0a3
#define ICON_FA_CHAIR "\xef\x9b\x80"	// U+f6c0
#define ICON_FA_CHALKBOARD "\xef\x94\x9b"	// U+f51b
#define ICON_FA_CHALKBOARD_TEACHER "\xef\x94\x9c"	// U+f51c
#define ICON_FA_CHARGING_STATION "\xef\x97\xa7"	// U+f5e7
#define ICON_FA_CHART_AREA "\xef\x87\xbe"	// U+f1fe
#define ICON_FA_CHART_BAR "\xef\x82\x80"	// U+f080
#define ICON_FA_CHART_LINE "\xef\x88\x81"	// U+f201
#define ICON_FA_CHART_PIE "\xef\x88\x80"	// U+f200
#define ICON_FA_CHECK "\xef\x80\x8c"	// U+f00c
#define ICON_FA_CHECK_CIRCLE "\xef\x81\x98"	// U+f058
#define ICON_FA_CHECK_DOUBLE "\xef\x95\xa0"	// U+f560
#define ICON_FA_CHECK_SQUARE "\xef\x85\x8a"	// U+f14a
#define ICON_FA_CHEESE "\xef\x9f\xaf"	// U+f7ef
#define ICON_FA_CHESS "\xef\x90\xb9"	// U+f439
#define ICON_FA_CHESS_BISHOP "\xef\x90\xba"	// U+f43a
#define ICON_FA_CHESS_BOARD "\xef\x90\xbc"	// U+f43c
#define ICON_FA_CHESS_KING "\xef\x90\xbf"	// U+f43f
#define ICON_FA_CHESS_KNIGHT "\xef\x91\x81"	// U+f441
#define ICON_FA_CHESS_PAWN "\xef\x91\x83"	// U+f443
#define ICON_FA_CHESS_QUEEN "\xef\x91\x85"	// U+f445
#define ICON_FA_CHESS_ROOK "\xef\x91\x87"	// U+f447
#define ICON_FA_CHEVRON_CIRCLE_DOWN "\xef\x84\xba"	// U+f13a
#define ICON_FA_CHEVRON_CIRCLE_LEFT "\xef\x84\xb7"	// U+f137
#define ICON_FA_CHEVRON_CIRCLE_RIGHT "\xef\x84\xb8"	// U+f138
#define ICON_FA_CHEVRON_CIRCLE_UP "\xef\x84\xb9"	// U+f139
#define ICON_FA_CHEVRON_DOWN "\xef\x81\xb8"	// U+f078
#define ICON_FA_CHEVRON_LEFT "\xef\x81\x93"	// U+f053
#define ICON_FA_CHEVRON_RIGHT "\xef\x81\x94"	// U+f054
#define ICON_FA_CHEVRON_UP "\xef\x81\xb7"	// U+f077
#define ICON_FA_CHILD "\xef\x86\xae"	// U+f1ae
#define ICON_FA_CHURCH "\xef\x94\x9d"	// U+f51d
#define ICON_FA_CIRCLE "\xef\x84\x91"	// U+f111
#define ICON_FA_CIRCLE_NOTCH "\xef\x87\x8e"	// U+f1ce
#define ICON_FA_CITY "\xef\x99\x8f"	// U+f64f
#define ICON_FA_CLINIC_MEDICAL "\xef\x9f\xb2"	// U+f7f2
#define ICON_FA_CLIPBOARD "\xef\x8c\xa8"	// U+f328
#define ICON_FA_CLIPBOARD_CHECK "\xef\x91\xac"	// U+f46c
#define ICON_FA_CLIPBOARD_LIST "\xef\x91\xad"	// U+f46d
#define ICON_FA_CLOCK "\xef\x80\x97"	// U+f017
#define ICON_FA_CLONE "\xef\x89\x8d"	// U+f24d
#define ICON_FA_CLOSED_CAPTIONING "\xef\x88\x8a"	// U+f20a
#define ICON_FA_CLOUD "\xef\x83\x82"	// U+f0c2
#define ICON_FA_CLOUD_DOWNLOAD_ALT "\xef\x8e\x81"	// U+f381
#define ICON_FA_CLOUD_MEATBALL "\xef\x9c\xbb"	// U+f73b
#define ICON_FA_CLOUD_MOON "\xef\x9b\x83"	// U+f6c3
#define ICON_FA_CLOUD_MOON_RAIN "\xef\x9c\xbc"	// U+f73c
#define ICON_FA_CLOUD_RAIN "\xef\x9c\xbd"	// U+f73d
#define ICON_FA_CLOUD_SHOWERS_HEAVY "\xef\x9d\x80"	// U+f740
#define ICON_FA_CLOUD_SUN "\xef\x9b\x84"	// U+f6c4
#define ICON_FA_CLOUD_SUN_RAIN "\xef\x9d\x83"	// U+f743
#define ICON_FA_CLOUD_UPLOAD_ALT "\xef\x8e\x82"	// U+f382
#define ICON_FA_COCKTAIL "\xef\x95\xa1"	// U+f561
#define ICON_FA_CODE "\xef\x84\xa1"	// U+f121
#define ICON_FA_CODE_BRANCH "\xef\x84\xa6"	// U+f126
#define ICON_FA_COFFEE "\xef\x83\xb4"	// U+f0f4
#define ICON_FA_COG "\xef\x80\x93"	// U+f013
#define ICON_FA_COGS "\xef\x82\x85"	// U+f085
#define ICON_FA_COINS "\xef\x94\x9e"	// U+f51e
#define ICON_FA_COLUMNS "\xef\x83\x9b"	// U+f0db
#define ICON_FA_COMMENT "\xef\x81\xb5"	// U+f075
#define ICON_FA_COMMENT_ALT "\xef\x89\xba"	// U+f27a
#define ICON_FA_COMMENT_DOLLAR "\xef\x99\x91"	// U+f651
#define ICON_FA_COMMENT_DOTS "\xef\x92\xad"	// U+f4ad
#define ICON_FA_COMMENT_MEDICAL "\xef\x9f\xb5"	// U+f7f5
#define ICON_FA_COMMENT_SLASH "\xef\x92\xb3"	// U+f4b3
#define ICON_FA_COMMENTS "\xef\x82\x86"	// U+f086
#define ICON_FA_COMMENTS_DOLLAR "\xef\x99\x93"	// U+f653
#define ICON_FA_COMPACT_DISC "\xef\x94\x9f"	// U+f51f
#define ICON_FA_COMPASS "\xef\x85\x8e"	// U+f14e
#define ICON_FA_COMPRESS "\xef\x81\xa6"	// U+f066
#define ICON_FA_COMPRESS_ALT "\xef\x90\xa2"	// U+f422
#define ICON_FA_COMPRESS_ARROWS_ALT "\xef\x9e\x8c"	// U+f78c
#define ICON_FA_CONCIERGE_BELL "\xef\x95\xa2"	// U+f562
#define ICON_FA_COOKIE "\xef\x95\xa3"	// U+f563
#define ICON_FA_COOKIE_BITE "\xef\x95\xa4"	// U+f564
#define ICON_FA_COPY "\xef\x83\x85"	// U+f0c5
#define ICON_FA_COPYRIGHT "\xef\x87\xb9"	// U+f1f9
#define ICON_FA_COUCH "\xef\x92\xb8"	// U+f4b8
#define ICON_FA_CREDIT_CARD "\xef\x82\x9d"	// U+f09d
#define ICON_FA_CROP "\xef\x84\xa5"	// U+f125
#define ICON_FA_CROP_ALT "\xef\x95\xa5"	// U+f565
#define ICON_FA_CROSS "\xef\x99\x94"	// U+f654
#define ICON_FA_CROSSHAIRS "\xef\x81\x9b"	// U+f05b
#define ICON_FA_CROW "\xef\x94\xa0"	// U+f520
#define ICON_FA_CROWN "\xef\x94\xa1"	// U+f521
#define ICON_FA_CRUTCH "\xef\x9f\xb7"	// U+f7f7
#define ICON_FA_CUBE "\xef\x86\xb2"	// U+f1b2
#define ICON_FA_CUBES "\xef\x86\xb3"	// U+f1b3
#define ICON_FA_CUT "\xef\x83\x84"	// U+f0c4
#define ICON_FA_DATABASE "\xef\x87\x80"	// U+f1c0
#define ICON_FA_DEAF "\xef\x8a\xa4"	// U+f2a4
#define ICON_FA_DEMOCRAT "\xef\x9d\x87"	// U+f747
#define ICON_FA_DESKTOP "\xef\x84\x88"	// U+f108
#define ICON_FA_DHARMACHAKRA "\xef\x99\x95"	// U+f655
#define ICON_FA_DIAGNOSES "\xef\x91\xb0"	// U+f470
#define ICON_FA_DICE "\xef\x94\xa2"	// U+f522
#define ICON_FA_DICE_D20 "\xef\x9b\x8f"	// U+f6cf
#define ICON_FA_DICE_D6 "\xef\x9b\x91"	// U+f6d1
#define ICON_FA_DICE_FIVE "\xef\x94\xa3"	// U+f523
#define ICON_FA_DICE_FOUR "\xef\x94\xa4"	// U+f524
#define ICON_FA_DICE_ONE "\xef\x94\xa5"	// U+f525
#define ICON_FA_DICE_SIX "\xef\x94\xa6"	// U+f526
#define ICON_FA_DICE_THREE "\xef\x94\xa7"	// U+f527
#define ICON_FA_DICE_TWO "\xef\x94\xa8"	// U+f528
#define ICON_FA_DIGITAL_TACHOGRAPH "\xef\x95\xa6"	// U+f566
#define ICON_FA_DIRECTIONS "\xef\x97\xab"	// U+f5eb
#define ICON_FA_DISEASE "\xef\x9f\xba"	// U+f7fa
#define ICON_FA_DIVIDE "\xef\x94\xa9"	// U+f529
#define ICON_FA_DIZZY "\xef\x95\xa7"	// U+f567
#define ICON_FA_DNA "\xef\x91\xb1"	// U+f471
#define ICON_FA_DOG "\xef\x9b\x93"	// U+f6d3
#define ICON_FA_DOLLAR_SIGN "\xef\x85\x95"	// U+f155
#define ICON_FA_DOLLY "\xef\x91\xb2"	// U+f472
#define ICON_FA_DOLLY_FLATBED "\xef\x91\xb4"	// U+f474
#define ICON_FA_DONATE "\xef\x92\xb9"	// U+f4b9
#define ICON_FA_DOOR_CLOSED "\xef\x94\xaa"	// U+f52a
#define ICON_FA_DOOR_OPEN "\xef\x94\xab"	// U+f52b
#define ICON_FA_DOT_CIRCLE "\xef\x86\x92"	// U+f192
#define ICON_FA_DOVE "\xef\x92\xba"	// U+f4ba
#define ICON_FA_DOWNLOAD "\xef\x80\x99"	// U+f019
#define ICON_FA_DRAFTING_COMPASS "\xef\x95\xa8"	// U+f568
#define ICON_FA_DRAGON "\xef\x9b\x95"	// U+f6d5
#define ICON_FA_DRAW_POLYGON "\xef\x97\xae"	// U+f5ee
#define ICON_FA_DRUM "\xef\x95\xa9"	// U+f569
#define ICON_FA_DRUM_STEELPAN "\xef\x95\xaa"	// U+f56a
#define ICON_FA_DRUMSTICK_BITE "\xef\x9b\x97"	// U+f6d7
#define ICON_FA_DUMBBELL "\xef\x91\x8b"	// U+f44b
#define ICON_FA_DUMPSTER "\xef\x9e\x93"	// U+f793
#define ICON_FA_DUMPSTER_FIRE "\xef\x9e\x94"	// U+f794
#define ICON_FA_DUNGEON "\xef\x9b\x99"	// U+f6d9
#define ICON_FA_EDIT "\xef\x81\x84"	// U+f044
#define ICON_FA_EGG "\xef\x9f\xbb"	// U+f7fb
#define ICON_FA_EJECT "\xef\x81\x92"	// U+f052
#define ICON_FA_ELLIPSIS_H "\xef\x85\x81"	// U+f141
#define ICON_FA_ELLIPSIS_V "\xef\x85\x82"	// U+f142
#define ICON_FA_ENVELOPE "\xef\x83\xa0"	// U+f0e0
#define ICON_FA_ENVELOPE_OPEN "\xef\x8a\xb6"	// U+f2b6
#define ICON_FA_ENVELOPE_OPEN_TEXT "\xef\x99\x98"	// U+f658
#define ICON_FA_ENVELOPE_SQUARE "\xef\x86\x99"	// U+f199
#define ICON_FA_EQUALS "\xef\x94\xac"	// U+f52c
#define ICON_FA_ERASER "\xef\x84\xad"	// U+f12d
#define ICON_FA_ETHERNET "\xef\x9e\x96"	// U+f796
#define ICON_FA_EURO_SIGN "\xef\x85\x93"	// U+f153
#define ICON_FA_EXCHANGE_ALT "\xef\x8d\xa2"	// U+f362
#define ICON_FA_EXCLAMATION "\xef\x84\xaa"	// U+f12a
#define ICON_FA_EXCLAMATION_CIRCLE "\xef\x81\xaa"	// U+f06a
#define ICON_FA_EXCLAMATION_TRIANGLE "\xef\x81\xb1"	// U+f071
#define ICON_FA_EXPAND "\xef\x81\xa5"	// U+f065
#define ICON_FA_EXPAND_ALT "\xef\x90\xa4"	// U+f424
#define ICON_FA_EXPAND_ARROWS_ALT "\xef\x8c\x9e"	// U+f31e
#define ICON_FA_EXTERNAL_LINK_ALT "\xef\x8d\x9d"	// U+f35d
#define ICON_FA_EXTERNAL_LINK_SQUARE_ALT "\xef\x8d\xa0"	// U+f360
#define ICON_FA_EYE "\xef\x81\xae"	// U+f06e
#define ICON_FA_EYE_DROPPER "\xef\x87\xbb"	// U+f1fb
#define ICON_FA_EYE_SLASH "\xef\x81\xb0"	// U+f070
#define ICON_FA_FAN "\xef\xa1\xa3"	// U+f863
#define ICON_FA_FAST_BACKWARD "\xef\x81\x89"	// U+f049
#define ICON_FA_FAST_FORWARD "\xef\x81\x90"	// U+f050
#define ICON_FA_FAUCET "\xee\x80\x85"	// U+e005
#define ICON_FA_FAX "\xef\x86\xac"	// U+f1ac
#define ICON_FA_FEATHER "\xef\x94\xad"	// U+f52d
#define ICON_FA_FEATHER_ALT "\xef\x95\xab"	// U+f56b
#define ICON_FA_FEMALE "\xef\x86\x82"	// U+f182
#define ICON_FA_FIGHTER_JET "\xef\x83\xbb"	// U+f0fb
#define ICON_FA_FILE "\xef\x85\x9b"	// U+f15b
#define ICON_FA_FILE_ALT "\xef\x85\x9c"	// U+f15c
#define ICON_FA_FILE_ARCHIVE "\xef\x87\x86"	// U+f1c6
#define ICON_FA_FILE_AUDIO "\xef\x87\x87"	// U+f1c7
#define ICON_FA_FILE_CODE "\xef\x87\x89"	// U+f1c9
#define ICON_FA_FILE_CONTRACT "\xef\x95\xac"	// U+f56c
#define ICON_FA_FILE_CSV "\xef\x9b\x9d"	// U+f6dd
#define ICON_FA_FILE_DOWNLOAD "\xef\x95\xad"	// U+f56d
#define ICON_FA_FILE_EXCEL "\xef\x87\x83"	// U+f1c3
#define ICON_FA_FILE_EXPORT "\xef\x95\xae"	// U+f56e
#define ICON_FA_FILE_IMAGE "\xef\x87\x85"	// U+f1c5
#define ICON_FA_FILE_IMPORT "\xef\x95\xaf"	// U+f56f
#define ICON_FA_FILE_INVOICE "\xef\x95\xb0"	// U+f570
#define ICON_FA_FILE_INVOICE_DOLLAR "\xef\x95\xb1"	// U+f571
#define ICON_FA_FILE_MEDICAL "\xef\x91\xb7"	// U+f477
#define ICON_FA_FILE_MEDICAL_ALT "\xef\x91\xb8"	// U+f478
#define ICON_FA_FILE_PDF "\xef\x87\x81"	// U+f1c1
#define ICON_FA_FILE_POWERPOINT "\xef\x87\x84"	// U+f1c4
#define ICON_FA_FILE_PRESCRIPTION "\xef\x95\xb2"	// U+f572
#define ICON_FA_FILE_SIGNATURE "\xef\x95\xb3"	// U+f573
#define ICON_FA_FILE_UPLOAD "\xef\x95\xb4"	// U+f574
#define ICON_FA_FILE_VIDEO "\xef\x87\x88"	// U+f1c8
#define ICON_FA_FILE_WORD "\xef\x87\x82"	// U+f1c2
#define ICON_FA_FILL "\xef\x95\xb5"	// U+f575
#define ICON_FA_FILL_DRIP "\xef\x95\xb6"	// U+f576
#define ICON_FA_FILM "\xef\x80\x88"	// U+f008
#define ICON_FA_FILTER "\xef\x82\xb0"	// U+f0b0
#define ICON_FA_FINGERPRINT "\xef\x95\xb7"	// U+f577
#define ICON_FA_FIRE "\xef\x81\xad"	// U+f06d
#define ICON_FA_FIRE_ALT "\xef\x9f\xa4"	// U+f7e4
#define ICON_FA_FIRE_EXTINGUISHER "\xef\x84\xb4"	// U+f134
#define ICON_FA_FIRST_AID "\xef\x91\xb9"	// U+f479
#define ICON_FA_FISH "\xef\x95\xb8"	// U+f578
#define ICON_FA_FIST_RAISED "\xef\x9b\x9e"	// U+f6de
#define ICON_FA_FLAG "\xef\x80\xa4"	// U+f024
#define ICON_FA_FLAG_CHECKERED "\xef\x84\x9e"	// U+f11e
#define ICON_FA_FLAG_USA "\xef\x9d\x8d"	// U+f74d
#define ICON_FA_FLASK "\xef\x83\x83"	// U+f0c3
#define ICON_FA_FLUSHED "\xef\x95\xb9"	// U+f579
#define ICON_FA_FOLDER "\xef\x81\xbb"	// U+f07b
#define ICON_FA_FOLDER_MINUS "\xef\x99\x9d"	// U+f65d
#define ICON_FA_FOLDER_OPEN "\xef\x81\xbc"	// U+f07c
#define ICON_FA_FOLDER_PLUS "\xef\x99\x9e"	// U+f65e
#define ICON_FA_FONT "\xef\x80\xb1"	// U+f031
#define ICON_FA_FONT_AWESOME_LOGO_FULL "\xef\x93\xa6"	// U+f4e6
#define ICON_FA_FOOTBALL_BALL "\xef\x91\x8e"	// U+f44e
#define ICON_FA_FORWARD "\xef\x81\x8e"	// U+f04e
#define ICON_FA_FROG "\xef\x94\xae"	// U+f52e
#define ICON_FA_FROWN "\xef\x84\x99"	// U+f119
#define ICON_FA_FROWN_OPEN "\xef\x95\xba"	// U+f57a
#define ICON_FA_FUNNEL_DOLLAR "\xef\x99\xa2"	// U+f662
#define ICON_FA_FUTBOL "\xef\x87\xa3"	// U+f1e3
#define ICON_FA_GAMEPAD "\xef\x84\x9b"	// U+f11b
#define ICON_FA_GAS_PUMP "\xef\x94\xaf"	// U+f52f
#define ICON_FA_GAVEL "\xef\x83\xa3"	// U+f0e3
#define ICON_FA_GEM "\xef\x8e\xa5"	// U+f3a5
#define ICON_FA_GENDERLESS "\xef\x88\xad"	// U+f22d
#define ICON_FA_GHOST "\xef\x9b\xa2"	// U+f6e2
#define ICON_FA_GIFT "\xef\x81\xab"	// U+f06b
#define ICON_FA_GIFTS "\xef\x9e\x9c"	// U+f79c
#define ICON_FA_GLASS_CHEERS "\xef\x9e\x9f"	// U+f79f
#define ICON_FA_GLASS_MARTINI "\xef\x80\x80"	// U+f000
#define ICON_FA_GLASS_MARTINI_ALT "\xef\x95\xbb"	// U+f57b
#define ICON_FA_GLASS_WHISKEY "\xef\x9e\xa0"	// U+f7a0
#define ICON_FA_GLASSES "\xef\x94\xb0"	// U+f530
#define ICON_FA_GLOBE "\xef\x82\xac"	// U+f0ac
#define ICON_FA_GLOBE_AFRICA "\xef\x95\xbc"	// U+f57c
#define ICON_FA_GLOBE_AMERICAS "\xef\x95\xbd"	// U+f57d
#define ICON_FA_GLOBE_ASIA "\xef\x95\xbe"	// U+f57e
#define ICON_FA_GLOBE_EUROPE "\xef\x9e\xa2"	// U+f7a2
#define ICON_FA_GOLF_BALL "\xef\x91\x90"	// U+f450
#define ICON_FA_GOPURAM "\xef\x99\xa4"	// U+f664
#define ICON_FA_GRADUATION_CAP "\xef\x86\x9d"	// U+f19d
#define ICON_FA_GREATER_THAN "\xef\x94\xb1"	// U+f531
#define ICON_FA_GREATER_THAN_EQUAL "\xef\x94\xb2"	// U+f532
#define ICON_FA_GRIMACE "\xef\x95\xbf"	// U+f57f
#define ICON_FA_GRIN "\xef\x96\x80"	// U+f580
#define ICON_FA_GRIN_ALT "\xef\x96\x81"	// U+f581
#define ICON_FA_GRIN_BEAM "\xef\x96\x82"	// U+f582
#define ICON_FA_GRIN_BEAM_SWEAT "\xef\x96\x83"	// U+f583
#define ICON_FA_GRIN_HEARTS "\xef\x96\x84"	// U+f584
#define ICON_FA_GRIN_SQUINT "\xef\x96\x85"	// U+f585
#define ICON_FA_GRIN_SQUINT_TEARS "\xef\x96\x86"	// U+f586
#define ICON_FA_GRIN_STARS "\xef\x96\x87"	// U+f587
#define ICON_FA_GRIN_TEARS "\xef\x96\x88"	// U+f588
#define ICON_FA_GRIN_TONGUE "\xef\x96\x89"	// U+f589
#define ICON_FA_GRIN_TONGUE_SQUINT "\xef\x96\x8a"	// U+f58a
#define ICON_FA_GRIN_TONGUE_WINK "\xef\x96\x8b"	// U+f58b
#define ICON_FA_GRIN_WINK "\xef\x96\x8c"	// U+f58c
#define ICON_FA_GRIP_HORIZONTAL "\xef\x96\x8d"	// U+f58d
#define ICON_FA_GRIP_LINES "\xef\x9e\xa4"	// U+f7a4
#define ICON_FA_GRIP_LINES_VERTICAL "\xef\x9e\xa5"	// U+f7a5
#define ICON_FA_GRIP_VERTICAL "\xef\x96\x8e"	// U+f58e
#define ICON_FA_GUITAR "\xef\x9e\xa6"	// U+f7a6
#define ICON_FA_H_SQUARE "\xef\x83\xbd"	// U+f0fd
#define ICON_FA_HAMBURGER "\xef\xa0\x85"	// U+f805
#define ICON_FA_HAMMER "\xef\x9b\xa3"	// U+f6e3
#define ICON_FA_HAMSA "\xef\x99\xa5"	// U+f665
#define ICON_FA_HAND_HOLDING "\xef\x92\xbd"	// U+f4bd
#define ICON_FA_HAND_HOLDING_HEART "\xef\x92\xbe"	// U+f4be
#define ICON_FA_HAND_HOLDING_MEDICAL "\xee\x81\x9c"	// U+e05c
#define ICON_FA_HAND_HOLDING_USD "\xef\x93\x80"	// U+f4c0
#define ICON_FA_HAND_HOLDING_WATER "\xef\x93\x81"	// U+f4c1
#define ICON_FA_HAND_LIZARD "\xef\x89\x98"	// U+f258
#define ICON_FA_HAND_MIDDLE_FINGER "\xef\xa0\x86"	// U+f806
#define ICON_FA_HAND_PAPER "\xef\x89\x96"	// U+f256
#define ICON_FA_HAND_PEACE "\xef\x89\x9b"	// U+f25b
#define ICON_FA_HAND_POINT_DOWN "\xef\x82\xa7"	// U+f0a7
#define ICON_FA_HAND_POINT_LEFT "\xef\x82\xa5"	// U+f0a5
#define ICON_FA_HAND_POINT_RIGHT "\xef\x82\xa4"	// U+f0a4
#define ICON_FA_HAND_POINT_UP "\xef\x82\xa6"	// U+f0a6
#define ICON_FA_HAND_POINTER "\xef\x89\x9a"	// U+f25a
#define ICON_FA_HAND_ROCK "\xef\x89\x95"	// U+f255
#define ICON_FA_HAND_SCISSORS "\xef\x89\x97"	// U+f257
#define ICON_FA_HAND_SPARKLES "\xee\x81\x9d"	// U+e05d
#define ICON_FA_HAND_SPOCK "\xef\x89\x99"	// U+f259
#define ICON_FA_HANDS "\xef\x93\x82"	// U+f4c2
#define ICON_FA_HANDS_HELPING "\xef\x93\x84"	// U+f4c4
#define ICON_FA_HANDS_WASH "\xee\x81\x9e"	// U+e05e
#define ICON_FA_HANDSHAKE "\xef\x8a\xb5"	// U+f2b5
#define ICON_FA_HANDSHAKE_ALT_SLASH "\xee\x81\x9f"	// U+e05f
#define ICON_FA_HANDSHAKE_SLASH "\xee\x81\xa0"	// U+e060
#define ICON_FA_HANUKIAH "\xef\x9b\xa6"	// U+f6e6
#define ICON_FA_HARD_HAT "\xef\xa0\x87"	// U+f807
#define ICON_FA_HASHTAG "\xef\x8a\x92"	// U+f292
#define ICON_FA_HAT_COWBOY "\xef\xa3\x80"	// U+f8c0
#define ICON_FA_HAT_COWBOY_SIDE "\xef\xa3\x81"	// U+f8c1
#define ICON_FA_HAT_WIZARD "\xef\x9b\xa8"	// U+f6e8
#define ICON_FA_HDD "\xef\x82\xa0"	// U+f0a0
#define ICON_FA_HEAD_SIDE_COUGH "\xee\x81\xa1"	// U+e061
#define ICON_FA_HEAD_SIDE_COUGH_SLASH "\xee\x81\xa2"	// U+e062
#define ICON_FA_HEAD_SIDE_MASK "\xee\x81\xa3"	// U+e063
#define ICON_FA_HEAD_SIDE_VIRUS "\xee\x81\xa4"	// U+e064
#define ICON_FA_HEADING "\xef\x87\x9c"	// U+f1dc
#define ICON_FA_HEADPHONES "\xef\x80\xa5"	// U+f025
#define ICON_FA_HEADPHONES_ALT "\xef\x96\x8f"	// U+f58f
#define ICON_FA_HEADSET "\xef\x96\x90"	// U+f590
#define ICON_FA_HEART "\xef\x80\x84"	// U+f004
#define ICON_FA_HEART_BROKEN "\xef\x9e\xa9"	// U+f7a9
#define ICON_FA_HEARTBEAT "\xef\x88\x9e"	// U+f21e
#define ICON_FA_HELICOPTER "\xef\x94\xb3"	// U+f533
#define ICON_FA_HIGHLIGHTER "\xef\x96\x91"	// U+f591
#define ICON_FA_HIKING "\xef\x9b\xac"	// U+f6ec
#define ICON_FA_HIPPO "\xef\x9b\xad"	// U+f6ed
#define ICON_FA_HISTORY "\xef\x87\x9a"	// U+f1da
#define ICON_FA_HOCKEY_PUCK "\xef\x91\x93"	// U+f453
#define ICON_FA_HOLLY_BERRY "\xef\x9e\xaa"	// U+f7aa
#define ICON_FA_HOME "\xef\x80\x95"	// U+f015
#define ICON_FA_HORSE "\xef\x9b\xb0"	// U+f6f0
#define ICON_FA_HORSE_HEAD "\xef\x9e\xab"	// U+f7ab
#define ICON_FA_HOSPITAL "\xef\x83\xb8"	// U+f0f8
#define ICON_FA_HOSPITAL_ALT "\xef\x91\xbd"	// U+f47d
#define ICON_FA_HOSPITAL_SYMBOL "\xef\x91\xbe"	// U+f47e
#define ICON_FA_HOSPITAL_USER "\xef\xa0\x8d"	// U+f80d
#define ICON_FA_HOT_TUB "\xef\x96\x93"	// U+f593
#define ICON_FA_HOTDOG "\xef\xa0\x8f"	// U+f80f
#define ICON_FA_HOTEL "\xef\x96\x94"	// U+f594
#define ICON_FA_HOURGLASS "\xef\x89\x94"	// U+f254
#define ICON_FA_HOURGLASS_END "\xef\x89\x93"	// U+f253
#define ICON_FA_HOURGLASS_HALF "\xef\x89\x92"	// U+f252
#define ICON_FA_HOURGLASS_START "\xef\x89\x91"	// U+f251
#define ICON_FA_HOUSE_DAMAGE "\xef\x9b\xb1"	// U+f6f1
#define ICON_FA_HOUSE_USER "\xee\x81\xa5"	// U+e065
#define ICON_FA_HRYVNIA "\xef\x9b\xb2"	// U+f6f2
#define ICON_FA_I_CURSOR "\xef\x89\x86"	// U+f246
#define ICON_FA_ICE_CREAM "\xef\xa0\x90"	// U+f810
#define ICON_FA_ICICLES "\xef\x9e\xad"	// U+f7ad
#define ICON_FA_ICONS "\xef\xa1\xad"	// U+f86d
#define ICON_FA_ID_BADGE "\xef\x8b\x81"	// U+f2c1
#define ICON_FA_ID_CARD "\xef\x8b\x82"	// U+f2c2
#define ICON_FA_ID_CARD_ALT "\xef\x91\xbf"	// U+f47f
#define ICON_FA_IGLOO "\xef\x9e\xae"	// U+f7ae
#define ICON_FA_IMAGE "\xef\x80\xbe"	// U+f03e
#define ICON_FA_IMAGES "\xef\x8c\x82"	// U+f302
#define ICON_FA_INBOX "\xef\x80\x9c"	// U+f01c
#define ICON_FA_INDENT "\xef\x80\xbc"	// U+f03c
#define ICON_FA_INDUSTRY "\xef\x89\xb5"	// U+f275
#define ICON_FA_INFINITY "\xef\x94\xb4"	// U+f534
#define ICON_FA_INFO "\xef\x84\xa9"	// U+f129
#define ICON_FA_INFO_CIRCLE "\xef\x81\x9a"	// U+f05a
#define ICON_FA_ITALIC "\xef\x80\xb3"	// U+f033
#define ICON_FA_JEDI "\xef\x99\xa9"	// U+f669
#define ICON_FA_JOINT "\xef\x96\x95"	// U+f595
#define ICON_FA_JOURNAL_WHILLS "\xef\x99\xaa"	// U+f66a
#define ICON_FA_KAABA "\xef\x99\xab"	// U+f66b
#define ICON_FA_KEY "\xef\x82\x84"	// U+f084
#define ICON_FA_KEYBOARD "\xef\x84\x9c"	// U+f11c
#define ICON_FA_KHANDA "\xef\x99\xad"	// U+f66d
#define ICON_FA_KISS "\xef\x96\x96"	// U+f596
#define ICON_FA_KISS_BEAM "\xef\x96\x97"	// U+f597
#define ICON_FA_KISS_WINK_HEART "\xef\x96\x98"	// U+f598
#define ICON_FA_KIWI_BIRD "\xef\x94\xb5"	// U+f535
#define ICON_FA_LANDMARK "\xef\x99\xaf"	// U+f66f
#define ICON_FA_LANGUAGE "\xef\x86\xab"	// U+f1ab
#define ICON_FA_LAPTOP "\xef\x84\x89"	// U+f109
#define ICON_FA_LAPTOP_CODE "\xef\x97\xbc"	// U+f5fc
#define ICON_FA_LAPTOP_HOUSE "\xee\x81\xa6"	// U+e066
#define ICON_FA_LAPTOP_MEDICAL "\xef\xa0\x92"	// U+f812
#define ICON_FA_LAUGH "\xef\x96\x99"	// U+f599
#define ICON_FA_LAUGH_BEAM "\xef\x96\x9a"	// U+f59a
#define ICON_FA_LAUGH_SQUINT "\xef\x96\x9b"	// U+f59b
#define ICON_FA_LAUGH_WINK "\xef\x96\x9c"	// U+f59c
#define ICON_FA_LAYER_GROUP "\xef\x97\xbd"	// U+f5fd
#define ICON_FA_LEAF "\xef\x81\xac"	// U+f06c
#define ICON_FA_LEMON "\xef\x82\x94"	// U+f094
#define ICON_FA_LESS_THAN "\xef\x94\xb6"	// U+f536
#define ICON_FA_LESS_THAN_EQUAL "\xef\x94\xb7"	// U+f537
#define ICON_FA_LEVEL_DOWN_ALT "\xef\x8e\xbe"	// U+f3be
#define ICON_FA_LEVEL_UP_ALT "\xef\x8e\xbf"	// U+f3bf
#define ICON_FA_LIFE_RING "\xef\x87\x8d"	// U+f1cd
#define ICON_FA_LIGHTBULB "\xef\x83\xab"	// U+f0eb
#define ICON_FA_LINK "\xef\x83\x81"	// U+f0c1
#define ICON_FA_LIRA_SIGN "\xef\x86\x95"	// U+f195
#define ICON_FA_LIST "\xef\x80\xba"	// U+f03a
#define ICON_FA_LIST_ALT "\xef\x80\xa2"	// U+f022
#define ICON_FA_LIST_OL "\xef\x83\x8b"	// U+f0cb
#define ICON_FA_LIST_UL "\xef\x83\x8a"	// U+f0ca
#define ICON_FA_LOCATION_ARROW "\xef\x84\xa4"	// U+f124
#define ICON_FA_LOCK "\xef\x80\xa3"	// U+f023
#define ICON_FA_LOCK_OPEN "\xef\x8f\x81"	// U+f3c1
#define ICON_FA_LONG_ARROW_ALT_DOWN "\xef\x8c\x89"	// U+f309
#define ICON_FA_LONG_ARROW_ALT_LEFT "\xef\x8c\x8a"	// U+f30a
#define ICON_FA_LONG_ARROW_ALT_RIGHT "\xef\x8c\x8b"	// U+f30b
#define ICON_FA_LONG_ARROW_ALT_UP "\xef\x8c\x8c"	// U+f30c
#define ICON_FA_LOW_VISION "\xef\x8a\xa8"	// U+f2a8
#define ICON_FA_LUGGAGE_CART "\xef\x96\x9d"	// U+f59d
#define ICON_FA_LUNGS "\xef\x98\x84"	// U+f604
#define ICON_FA_LUNGS_VIRUS "\xee\x81\xa7"	// U+e067
#define ICON_FA_MAGIC "\xef\x83\x90"	// U+f0d0
#define ICON_FA_MAGNET "\xef\x81\xb6"	// U+f076
#define ICON_FA_MAIL_BULK "\xef\x99\xb4"	// U+f674
#define ICON_FA_MALE "\xef\x86\x83"	// U+f183
#define ICON_FA_MAP "\xef\x89\xb9"	// U+f279
#define ICON_FA_MAP_MARKED "\xef\x96\x9f"	// U+f59f
#define ICON_FA_MAP_MARKED_ALT "\xef\x96\xa0"	// U+f5a0
#define ICON_FA_MAP_MARKER "\xef\x81\x81"	// U+f041
#define ICON_FA_MAP_MARKER_ALT "\xef\x8f\x85"	// U+f3c5
#define ICON_FA_MAP_PIN "\xef\x89\xb6"	// U+f276
#define ICON_FA_MAP_SIGNS "\xef\x89\xb7"	// U+f277
#define ICON_FA_MARKER "\xef\x96\xa1"	// U+f5a1
#define ICON_FA_MARS "\xef\x88\xa2"	// U+f222
#define ICON_FA_MARS_DOUBLE "\xef\x88\xa7"	// U+f227
#define ICON_FA_MARS_STROKE "\xef\x88\xa9"	// U+f229
#define ICON_FA_MARS_STROKE_H "\xef\x88\xab"	// U+f22b
#define ICON_FA_MARS_STROKE_V "\xef\x88\xaa"	// U+f22a
#define ICON_FA_MASK "\xef\x9b\xba"	// U+f6fa
#define ICON_FA_MEDAL "\xef\x96\xa2"	// U+f5a2
#define ICON_FA_MEDKIT "\xef\x83\xba"	// U+f0fa
#define ICON_FA_MEH "\xef\x84\x9a"	// U+f11a
#define ICON_FA_MEH_BLANK "\xef\x96\xa4"	// U+f5a4
#define ICON_FA_MEH_ROLLING_EYES "\xef\x96\xa5"	// U+f5a5
#define ICON_FA_MEMORY "\xef\x94\xb8"	// U+f538
#define ICON_FA_MENORAH "\xef\x99\xb6"	// U+f676
#define ICON_FA_MERCURY "\xef\x88\xa3"	// U+f223
#define ICON_FA_METEOR "\xef\x9d\x93"	// U+f753
#define ICON_FA_MICROCHIP "\xef\x8b\x9b"	// U+f2db
#define ICON_FA_MICROPHONE "\xef\x84\xb0"	// U+f130
#define ICON_FA_MICROPHONE_ALT "\xef\x8f\x89"	// U+f3c9
#define ICON_FA_MICROPHONE_ALT_SLASH "\xef\x94\xb9"	// U+f539
#define ICON_FA_MICROPHONE_SLASH "\xef\x84\xb1"	// U+f131
#define ICON_FA_MICROSCOPE "\xef\x98\x90"	// U+f610
#define ICON_FA_MINUS "\xef\x81\xa8"	// U+f068
#define ICON_FA_MINUS_CIRCLE "\xef\x81\x96"	// U+f056
#define ICON_FA_MINUS_SQUARE "\xef\x85\x86"	// U+f146
#define ICON_FA_MITTEN "\xef\x9e\xb5"	// U+f7b5
#define ICON_FA_MOBILE "\xef\x84\x8b"	// U+f10b
#define ICON_FA_MOBILE_ALT "\xef\x8f\x8d"	// U+f3cd
#define ICON_FA_MONEY_BILL "\xef\x83\x96"	// U+f0d6
#define ICON_FA_MONEY_BILL_ALT "\xef\x8f\x91"	// U+f3d1
#define ICON_FA_MONEY_BILL_WAVE "\xef\x94\xba"	// U+f53a
#define ICON_FA_MONEY_BILL_WAVE_ALT "\xef\x94\xbb"	// U+f53b
#define ICON_FA_MONEY_CHECK "\xef\x94\xbc"	// U+f53c
#define ICON_FA_MONEY_CHECK_ALT "\xef\x94\xbd"	// U+f53d
#define ICON_FA_MONUMENT "\xef\x96\xa6"	// U+f5a6
#define ICON_FA_MOON "\xef\x86\x86"	// U+f186
#define ICON_FA_MORTAR_PESTLE "\xef\x96\xa7"	// U+f5a7
#define ICON_FA_MOSQUE "\xef\x99\xb8"	// U+f678
#define ICON_FA_MOTORCYCLE "\xef\x88\x9c"	// U+f21c
#define ICON_FA_MOUNTAIN "\xef\x9b\xbc"	// U+f6fc
#define ICON_FA_MOUSE "\xef\xa3\x8c"	// U+f8cc
#define ICON_FA_MOUSE_POINTER "\xef\x89\x85"	// U+f245
#define ICON_FA_MUG_HOT "\xef\x9e\xb6"	// U+f7b6
#define ICON_FA_MUSIC "\xef\x80\x81"	// U+f001
#define ICON_FA_NETWORK_WIRED "\xef\x9b\xbf"	// U+f6ff
#define ICON_FA_NEUTER "\xef\x88\xac"	// U+f22c
#define ICON_FA_NEWSPAPER "\xef\x87\xaa"	// U+f1ea
#define ICON_FA_NOT_EQUAL "\xef\x94\xbe"	// U+f53e
#define ICON_FA_NOTES_MEDICAL "\xef\x92\x81"	// U+f481
#define ICON_FA_OBJECT_GROUP "\xef\x89\x87"	// U+f247
#define ICON_FA_OBJECT_UNGROUP "\xef\x89\x88"	// U+f248
#define ICON_FA_OIL_CAN "\xef\x98\x93"	// U+f613
#define ICON_FA_OM "\xef\x99\xb9"	// U+f679
#define ICON_FA_OTTER "\xef\x9c\x80"	// U+f700
#define ICON_FA_OUTDENT "\xef\x80\xbb"	// U+f03b
#define ICON_FA_PAGER "\xef\xa0\x95"	// U+f815
#define ICON_FA_PAINT_BRUSH "\xef\x87\xbc"	// U+f1fc
#define ICON_FA_PAINT_ROLLER "\xef\x96\xaa"	// U+f5aa
#define ICON_FA_PALETTE "\xef\x94\xbf"	// U+f53f
#define ICON_FA_PALLET "\xef\x92\x82"	// U+f482
#define ICON_FA_PAPER_PLANE "\xef\x87\x98"	// U+f1d8
#define ICON_FA_PAPERCLIP "\xef\x83\x86"	// U+f0c6
#define ICON_FA_PARACHUTE_BOX "\xef\x93\x8d"	// U+f4cd
#define ICON_FA_PARAGRAPH "\xef\x87\x9d"	// U+f1dd
#define ICON_FA_PARKING "\xef\x95\x80"	// U+f540
#define ICON_FA_PASSPORT "\xef\x96\xab"	// U+f5ab
#define ICON_FA_PASTAFARIANISM "\xef\x99\xbb"	// U+f67b
#define ICON_FA_PASTE "\xef\x83\xaa"	// U+f0ea
#define ICON_FA_PAUSE "\xef\x81\x8c"	// U+f04c
#define ICON_FA_PAUSE_CIRCLE "\xef\x8a\x8b"	// U+f28b
#define ICON_FA_PAW "\xef\x86\xb0"	// U+f1b0
#define ICON_FA_PEACE "\xef\x99\xbc"	// U+f67c
#define ICON_FA_PEN "\xef\x8c\x84"	// U+f304
#define ICON_FA_PEN_ALT "\xef\x8c\x85"	// U+f305
#define ICON_FA_PEN_FANCY "\xef\x96\xac"	// U+f5ac
#define ICON_FA_PEN_NIB "\xef\x96\xad"	// U+f5ad
#define ICON_FA_PEN_SQUARE "\xef\x85\x8b"	// U+f14b
#define ICON_FA_PENCIL_ALT "\xef\x8c\x83"	// U+f303
#define ICON_FA_PENCIL_RULER "\xef\x96\xae"	// U+f5ae
#define ICON_FA_PEOPLE_ARROWS "\xee\x81\xa8"	// U+e068
#define ICON_FA_PEOPLE_CARRY "\xef\x93\x8e"	// U+f4ce
#define ICON_FA_PEPPER_HOT "\xef\xa0\x96"	// U+f816
#define ICON_FA_PERCENT "\xef\x8a\x95"	// U+f295
#define ICON_FA_PERCENTAGE "\xef\x95\x81"	// U+f541
#define ICON_FA_PERSON_BOOTH "\xef\x9d\x96"	// U+f756
#define ICON_FA_PHONE "\xef\x82\x95"	// U+f095
#define ICON_FA_PHONE_ALT "\xef\xa1\xb9"	// U+f879
#define ICON_FA_PHONE_SLASH "\xef\x8f\x9d"	// U+f3dd
#define ICON_FA_PHONE_SQUARE "\xef\x82\x98"	// U+f098
#define ICON_FA_PHONE_SQUARE_ALT "\xef\xa1\xbb"	// U+f87b
#define ICON_FA_PHONE_VOLUME "\xef\x8a\xa0"	// U+f2a0
#define ICON_FA_PHOTO_VIDEO "\xef\xa1\xbc"	// U+f87c
#define ICON_FA_PIGGY_BANK "\xef\x93\x93"	// U+f4d3
#define ICON_FA_PILLS "\xef\x92\x84"	// U+f484
#define ICON_FA_PIZZA_SLICE "\xef\xa0\x98"	// U+f818
#define ICON_FA_PLACE_OF_WORSHIP "\xef\x99\xbf"	// U+f67f
#define ICON_FA_PLANE "\xef\x81\xb2"	// U+f072
#define ICON_FA_PLANE_ARRIVAL "\xef\x96\xaf"	// U+f5af
#define ICON_FA_PLANE_DEPARTURE "\xef\x96\xb0"	// U+f5b0
#define ICON_FA_PLANE_SLASH "\xee\x81\xa9"	// U+e069
#define ICON_FA_PLAY "\xef\x81\x8b"	// U+f04b
#define ICON_FA_PLAY_CIRCLE "\xef\x85\x84"	// U+f144
#define ICON_FA_PLUG "\xef\x87\xa6"	// U+f1e6
#define ICON_FA_PLUS "\xef\x81\xa7"	// U+f067
#define ICON_FA_PLUS_CIRCLE "\xef\x81\x95"	// U+f055
#define ICON_FA_PLUS_SQUARE "\xef\x83\xbe"	// U+f0fe
#define ICON_FA_PODCAST "\xef\x8b\x8e"	// U+f2ce
#define ICON_FA_POLL "\xef\x9a\x81"	// U+f681
#define ICON_FA_POLL_H "\xef\x9a\x82"	// U+f682
#define ICON_FA_POO "\xef\x8b\xbe"	// U+f2fe
#define ICON_FA_POO_STORM "\xef\x9d\x9a"	// U+f75a
#define ICON_FA_POOP "\xef\x98\x99"	// U+f619
#define ICON_FA_PORTRAIT "\xef\x8f\xa0"	// U+f3e0
#define ICON_FA_POUND_SIGN "\xef\x85\x94"	// U+f154
#define ICON_FA_POWER_OFF "\xef\x80\x91"	// U+f011
#define ICON_FA_PRAY "\xef\x9a\x83"	// U+f683
#define ICON_FA_PRAYING_HANDS "\xef\x9a\x84"	// U+f684
#define ICON_FA_PRESCRIPTION "\xef\x96\xb1"	// U+f5b1
#define ICON_FA_PRESCRIPTION_BOTTLE "\xef\x92\x85"	// U+f485
#define ICON_FA_PRESCRIPTION_BOTTLE_ALT "\xef\x92\x86"	// U+f486
#define ICON_FA_PRINT "\xef\x80\xaf"	// U+f02f
#define ICON_FA_PROCEDURES "\xef\x92\x87"	// U+f487
#define ICON_FA_PROJECT_DIAGRAM "\xef\x95\x82"	// U+f542
#define ICON_FA_PUMP_MEDICAL "\xee\x81\xaa"	// U+e06a
#define ICON_FA_PUMP_SOAP "\xee\x81\xab"	// U+e06b
#define ICON_FA_PUZZLE_PIECE "\xef\x84\xae"	// U+f12e
#define ICON_FA_QRCODE "\xef\x80\xa9"	// U+f029
#define ICON_FA_QUESTION "\xef\x84\xa8"	// U+f128
#define ICON_FA_QUESTION_CIRCLE "\xef\x81\x99"	// U+f059
#define ICON_FA_QUIDDITCH "\xef\x91\x98"	// U+f458
#define ICON_FA_QUOTE_LEFT "\xef\x84\x8d"	// U+f10d
#define ICON_FA_QUOTE_RIGHT "\xef\x84\x8e"	// U+f10e
#define ICON_FA_QURAN "\xef\x9a\x87"	// U+f687
#define ICON_FA_RADIATION "\xef\x9e\xb9"	// U+f7b9
#define ICON_FA_RADIATION_ALT "\xef\x9e\xba"	// U+f7ba
#define ICON_FA_RAINBOW "\xef\x9d\x9b"	// U+f75b
#define ICON_FA_RANDOM "\xef\x81\xb4"	// U+f074
#define ICON_FA_RECEIPT "\xef\x95\x83"	// U+f543
#define ICON_FA_RECORD_VINYL "\xef\xa3\x99"	// U+f8d9
#define ICON_FA_RECYCLE "\xef\x86\xb8"	// U+f1b8
#define ICON_FA_REDO "\xef\x80\x9e"	// U+f01e
#define ICON_FA_REDO_ALT "\xef\x8b\xb9"	// U+f2f9
#define ICON_FA_REGISTERED "\xef\x89\x9d"	// U+f25d
#define ICON_FA_REMOVE_FORMAT "\xef\xa1\xbd"	// U+f87d
#define ICON_FA_REPLY "\xef\x8f\xa5"	// U+f3e5
#define ICON_FA_REPLY_ALL "\xef\x84\xa2"	// U+f122
#define ICON_FA_REPUBLICAN "\xef\x9d\x9e"	// U+f75e
#define ICON_FA_RESTROOM "\xef\x9e\xbd"	// U+f7bd
#define ICON_FA_RETWEET "\xef\x81\xb9"	// U+f079
#define ICON_FA_RIBBON "\xef\x93\x96"	// U+f4d6
#define ICON_FA_RING "\xef\x9c\x8b"	// U+f70b
#define ICON_FA_ROAD "\xef\x80\x98"	// U+f018
#define ICON_FA_ROBOT "\xef\x95\x84"	// U+f544
#define ICON_FA_ROCKET "\xef\x84\xb5"	// U+f135
#define ICON_FA_ROUTE "\xef\x93\x97"	// U+f4d7
#define ICON_FA_RSS "\xef\x82\x9e"	// U+f09e
#define ICON_FA_RSS_SQUARE "\xef\x85\x83"	// U+f143
#define ICON_FA_RUBLE_SIGN "\xef\x85\x98"	// U+f158
#define ICON_FA_RULER "\xef\x95\x85"	// U+f545
#define ICON_FA_RULER_COMBINED "\xef\x95\x86"	// U+f546
#define ICON_FA_RULER_HORIZONTAL "\xef\x95\x87"	// U+f547
#define ICON_FA_RULER_VERTICAL "\xef\x95\x88"	// U+f548
#define ICON_FA_RUNNING "\xef\x9c\x8c"	// U+f70c
#define ICON_FA_RUPEE_SIGN "\xef\x85\x96"	// U+f156
#define ICON_FA_SAD_CRY "\xef\x96\xb3"	// U+f5b3
#define ICON_FA_SAD_TEAR "\xef\x96\xb4"	// U+f5b4
#define ICON_FA_SATELLITE "\xef\x9e\xbf"	// U+f7bf
#define ICON_FA_SATELLITE_DISH "\xef\x9f\x80"	// U+f7c0
#define ICON_FA_SAVE "\xef\x83\x87"	// U+f0c7
#define ICON_FA_SCHOOL "\xef\x95\x89"	// U+f549
#define ICON_FA_SCREWDRIVER "\xef\x95\x8a"	// U+f54a
#define ICON_FA_SCROLL "\xef\x9c\x8e"	// U+f70e
#define ICON_FA_SD_CARD "\xef\x9f\x82"	// U+f7c2
#define ICON_FA_SEARCH "\xef\x80\x82"	// U+f002
#define ICON_FA_SEARCH_DOLLAR "\xef\x9a\x88"	// U+f688
#define ICON_FA_SEARCH_LOCATION "\xef\x9a\x89"	// U+f689
#define ICON_FA_SEARCH_MINUS "\xef\x80\x90"	// U+f010
#define ICON_FA_SEARCH_PLUS "\xef\x80\x8e"	// U+f00e
#define ICON_FA_SEEDLING "\xef\x93\x98"	// U+f4d8
#define ICON_FA_SERVER "\xef\x88\xb3"	// U+f233
#define ICON_FA_SHAPES "\xef\x98\x9f"	// U+f61f
#define ICON_FA_SHARE "\xef\x81\xa4"	// U+f064
#define ICON_FA_SHARE_ALT "\xef\x87\xa0"	// U+f1e0
#define ICON_FA_SHARE_ALT_SQUARE "\xef\x87\xa1"	// U+f1e1
#define ICON_FA_SHARE_SQUARE "\xef\x85\x8d"	// U+f14d
#define ICON_FA_SHEKEL_SIGN "\xef\x88\x8b"	// U+f20b
#define ICON_FA_SHIELD_ALT "\xef\x8f\xad"	// U+f3ed
#define ICON_FA_SHIELD_VIRUS "\xee\x81\xac"	// U+e06c
#define ICON_FA_SHIP "\xef\x88\x9a"	// U+f21a
#define ICON_FA_SHIPPING_FAST "\xef\x92\x8b"	// U+f48b
#define ICON_FA_SHOE_PRINTS "\xef\x95\x8b"	// U+f54b
#define ICON_FA_SHOPPING_BAG "\xef\x8a\x90"	// U+f290
#define ICON_FA_SHOPPING_BASKET "\xef\x8a\x91"	// U+f291
#define ICON_FA_SHOPPING_CART "\xef\x81\xba"	// U+f07a
#define ICON_FA_SHOWER "\xef\x8b\x8c"	// U+f2cc
#define ICON_FA_SHUTTLE_VAN "\xef\x96\xb6"	// U+f5b6
#define ICON_FA_SIGN "\xef\x93\x99"	// U+f4d9
#define ICON_FA_SIGN_IN_ALT "\xef\x8b\xb6"	// U+f2f6
#define ICON_FA_SIGN_LANGUAGE "\xef\x8a\xa7"	// U+f2a7
#define ICON_FA_SIGN_OUT_ALT "\xef\x8b\xb5"	// U+f2f5
#define ICON_FA_SIGNAL "\xef\x80\x92"	// U+f012
#define ICON_FA_SIGNATURE "\xef\x96\xb7"	// U+f5b7
#define ICON_FA_SIM_CARD "\xef\x9f\x84"	// U+f7c4
#define ICON_FA_SINK "\xee\x81\xad"	// U+e06d
#define ICON_FA_SITEMAP "\xef\x83\xa8"	// U+f0e8
#define ICON_FA_SKATING "\xef\x9f\x85"	// U+f7c5
#define ICON_FA_SKIING "\xef\x9f\x89"	// U+f7c9
#define ICON_FA_SKIING_NORDIC "\xef\x9f\x8a"	// U+f7ca
#define ICON_FA_SKULL "\xef\x95\x8c"	// U+f54c
#define ICON_FA_SKULL_CROSSBONES "\xef\x9c\x94"	// U+f714
#define ICON_FA_SLASH "\xef\x9c\x95"	// U+f715
#define ICON_FA_SLEIGH "\xef\x9f\x8c"	// U+f7cc
#define ICON_FA_SLIDERS_H "\xef\x87\x9e"	// U+f1de
#define ICON_FA_SMILE "\xef\x84\x98"	// U+f118
#define ICON_FA_SMILE_BEAM "\xef\x96\xb8"	// U+f5b8
#define ICON_FA_SMILE_WINK "\xef\x93\x9a"	// U+f4da
#define ICON_FA_SMOG "\xef\x9d\x9f"	// U+f75f
#define ICON_FA_SMOKING "\xef\x92\x8d"	// U+f48d
#define ICON_FA_SMOKING_BAN "\xef\x95\x8d"	// U+f54d
#define ICON_FA_SMS "\xef\x9f\x8d"	// U+f7cd
#define ICON_FA_SNOWBOARDING "\xef\x9f\x8e"	// U+f7ce
#define ICON_FA_SNOWFLAKE "\xef\x8b\x9c"	// U+f2dc
#define ICON_FA_SNOWMAN "\xef\x9f\x90"	// U+f7d0
#define ICON_FA_SNOWPLOW "\xef\x9f\x92"	// U+f7d2
#define ICON_FA_SOAP "\xee\x81\xae"	// U+e06e
#define ICON_FA_SOCKS "\xef\x9a\x96"	// U+f696
#define ICON_FA_SOLAR_PANEL "\xef\x96\xba"	// U+f5ba
#define ICON_FA_SORT "\xef\x83\x9c"	// U+f0dc
#define ICON_FA_SORT_ALPHA_DOWN "\xef\x85\x9d"	// U+f15d
#define ICON_FA_SORT_ALPHA_DOWN_ALT "\xef\xa2\x81"	// U+f881
#define ICON_FA_SORT_ALPHA_UP "\xef\x85\x9e"	// U+f15e
#define ICON_FA_SORT_ALPHA_UP_ALT "\xef\xa2\x82"	// U+f882
#define ICON_FA_SORT_AMOUNT_DOWN "\xef\x85\xa0"	// U+f160
#define ICON_FA_SORT_AMOUNT_DOWN_ALT "\xef\xa2\x84"	// U+f884
#define ICON_FA_SORT_AMOUNT_UP "\xef\x85\xa1"	// U+f161
#define ICON_FA_SORT_AMOUNT_UP_ALT "\xef\xa2\x85"	// U+f885
#define ICON_FA_SORT_DOWN "\xef\x83\x9d"	// U+f0dd
#define ICON_FA_SORT_NUMERIC_DOWN "\xef\x85\xa2"	// U+f162
#define ICON_FA_SORT_NUMERIC_DOWN_ALT "\xef\xa2\x86"	// U+f886
#define ICON_FA_SORT_NUMERIC_UP "\xef\x85\xa3"	// U+f163
#define ICON_FA_SORT_NUMERIC_UP_ALT "\xef\xa2\x87"	// U+f887
#define ICON_FA_SORT_UP "\xef\x83\x9e"	// U+f0de
#define ICON_FA_SPA "\xef\x96\xbb"	// U+f5bb
#define ICON_FA_SPACE_SHUTTLE "\xef\x86\x97"	// U+f197
#define ICON_FA_SPELL_CHECK "\xef\xa2\x91"	// U+f891
#define ICON_FA_SPIDER "\xef\x9c\x97"	// U+f717
#define ICON_FA_SPINNER "\xef\x84\x90"	// U+f110
#define ICON_FA_SPLOTCH "\xef\x96\xbc"	// U+f5bc
#define ICON_FA_SPRAY_CAN "\xef\x96\xbd"	// U+f5bd
#define ICON_FA_SQUARE "\xef\x83\x88"	// U+f0c8
#define ICON_FA_SQUARE_FULL "\xef\x91\x9c"	// U+f45c
#define ICON_FA_SQUARE_ROOT_ALT "\xef\x9a\x98"	// U+f698
#define ICON_FA_STAMP "\xef\x96\xbf"	// U+f5bf
#define ICON_FA_STAR "\xef\x80\x85"	// U+f005
#define ICON_FA_STAR_AND_CRESCENT "\xef\x9a\x99"	// U+f699
#define ICON_FA_STAR_HALF "\xef\x82\x89"	// U+f089
#define ICON_FA_STAR_HALF_ALT "\xef\x97\x80"	// U+f5c0
#define ICON_FA_STAR_OF_DAVID "\xef\x9a\x9a"	// U+f69a
#define ICON_FA_STAR_OF_LIFE "\xef\x98\xa1"	// U+f621
#define ICON_FA_STEP_BACKWARD "\xef\x81\x88"	// U+f048
#define ICON_FA_STEP_FORWARD "\xef\x81\x91"	// U+f051
#define ICON_FA_STETHOSCOPE "\xef\x83\xb1"	// U+f0f1
#define ICON_FA_STICKY_NOTE "\xef\x89\x89"	// U+f249
#define ICON_FA_STOP "\xef\x81\x8d"	// U+f04d
#define ICON_FA_STOP_CIRCLE "\xef\x8a\x8d"	// U+f28d
#define ICON_FA_STOPWATCH "\xef\x8b\xb2"	// U+f2f2
#define ICON_FA_STOPWATCH_20 "\xee\x81\xaf"	// U+e06f
#define ICON_FA_STORE "\xef\x95\x8e"	// U+f54e
#define ICON_FA_STORE_ALT "\xef\x95\x8f"	// U+f54f
#define ICON_FA_STORE_ALT_SLASH "\xee\x81\xb0"	// U+e070
#define ICON_FA_STORE_SLASH "\xee\x81\xb1"	// U+e071
#define ICON_FA_STREAM "\xef\x95\x90"	// U+f550
#define ICON_FA_STREET_VIEW "\xef\x88\x9d"	// U+f21d
#define ICON_FA_STRIKETHROUGH "\xef\x83\x8c"	// U+f0cc
#define ICON_FA_STROOPWAFEL "\xef\x95\x91"	// U+f551
#define ICON_FA_SUBSCRIPT "\xef\x84\xac"	// U+f12c
#define ICON_FA_SUBWAY "\xef\x88\xb9"	// U+f239
#define ICON_FA_SUITCASE "\xef\x83\xb2"	// U+f0f2
#define ICON_FA_SUITCASE_ROLLING "\xef\x97\x81"	// U+f5c1
#define ICON_FA_SUN "\xef\x86\x85"	// U+f185
#define ICON_FA_SUPERSCRIPT "\xef\x84\xab"	// U+f12b
#define ICON_FA_SURPRISE "\xef\x97\x82"	// U+f5c2
#define ICON_FA_SWATCHBOOK "\xef\x97\x83"	// U+f5c3
#define ICON_FA_SWIMMER "\xef\x97\x84"	// U+f5c4
#define ICON_FA_SWIMMING_POOL "\xef\x97\x85"	// U+f5c5
#define ICON_FA_SYNAGOGUE "\xef\x9a\x9b"	// U+f69b
#define ICON_FA_SYNC "\xef\x80\xa1"	// U+f021
#define ICON_FA_SYNC_ALT "\xef\x8b\xb1"	// U+f2f1
#define ICON_FA_SYRINGE "\xef\x92\x8e"	// U+f48e
#define ICON_FA_TABLE "\xef\x83\x8e"	// U+f0ce
#define ICON_FA_TABLE_TENNIS "\xef\x91\x9d"	// U+f45d
#define ICON_FA_TABLET "\xef\x84\x8a"	// U+f10a
#define ICON_FA_TABLET_ALT "\xef\x8f\xba"	// U+f3fa
#define ICON_FA_TABLETS "\xef\x92\x90"	// U+f490
#define ICON_FA_TACHOMETER_ALT "\xef\x8f\xbd"	// U+f3fd
#define ICON_FA_TAG "\xef\x80\xab"	// U+f02b
#define ICON_FA_TAGS "\xef\x80\xac"	// U+f02c
#define ICON_FA_TAPE "\xef\x93\x9b"	// U+f4db
#define ICON_FA_TASKS "\xef\x82\xae"	// U+f0ae
#define ICON_FA_TAXI "\xef\x86\xba"	// U+f1ba
#define ICON_FA_TEETH "\xef\x98\xae"	// U+f62e
#define ICON_FA_TEETH_OPEN "\xef\x98\xaf"	// U+f62f
#define ICON_FA_TEMPERATURE_HIGH "\xef\x9d\xa9"	// U+f769
#define ICON_FA_TEMPERATURE_LOW "\xef\x9d\xab"	// U+f76b
#define ICON_FA_TENGE "\xef\x9f\x97"	// U+f7d7
#define ICON_FA_TERMINAL "\xef\x84\xa0"	// U+f120
#define ICON_FA_TEXT_HEIGHT "\xef\x80\xb4"	// U+f034
#define ICON_FA_TEXT_WIDTH "\xef\x80\xb5"	// U+f035
#define ICON_FA_TH "\xef\x80\x8a"	// U+f00a
#define ICON_FA_TH_LARGE "\xef\x80\x89"	// U+f009
#define ICON_FA_TH_LIST "\xef\x80\x8b"	// U+f00b
#define ICON_FA_THEATER_MASKS "\xef\x98\xb0"	// U+f630
#define ICON_FA_THERMOMETER "\xef\x92\x91"	// U+f491
#define ICON_FA_THERMOMETER_EMPTY "\xef\x8b\x8b"	// U+f2cb
#define ICON_FA_THERMOMETER_FULL "\xef\x8b\x87"	// U+f2c7
#define ICON_FA_THERMOMETER_HALF "\xef\x8b\x89"	// U+f2c9
#define ICON_FA_THERMOMETER_QUARTER "\xef\x8b\x8a"	// U+f2ca
#define ICON_FA_THERMOMETER_THREE_QUARTERS "\xef\x8b\x88"	// U+f2c8
#define ICON_FA_THUMBS_DOWN "\xef\x85\xa5"	// U+f165
#define ICON_FA_THUMBS_UP "\xef\x85\xa4"	// U+f164
#define ICON_FA_THUMBTACK "\xef\x82\x8d"	// U+f08d
#define ICON_FA_TICKET_ALT "\xef\x8f\xbf"	// U+f3ff
#define ICON_FA_TIMES "\xef\x80\x8d"	// U+f00d
#define ICON_FA_TIMES_CIRCLE "\xef\x81\x97"	// U+f057
#define ICON_FA_TINT "\xef\x81\x83"	// U+f043
#define ICON_FA_TINT_SLASH "\xef\x97\x87"	// U+f5c7
#define ICON_FA_TIRED "\xef\x97\x88"	// U+f5c8
#define ICON_FA_TOGGLE_OFF "\xef\x88\x84"	// U+f204
#define ICON_FA_TOGGLE_ON "\xef\x88\x85"	// U+f205
#define ICON_FA_TOILET "\xef\x9f\x98"	// U+f7d8
#define ICON_FA_TOILET_PAPER "\xef\x9c\x9e"	// U+f71e
#define ICON_FA_TOILET_PAPER_SLASH "\xee\x81\xb2"	// U+e072
#define ICON_FA_TOOLBOX "\xef\x95\x92"	// U+f552
#define ICON_FA_TOOLS "\xef\x9f\x99"	// U+f7d9
#define ICON_FA_TOOTH "\xef\x97\x89"	// U+f5c9
#define ICON_FA_TORAH "\xef\x9a\xa0"	// U+f6a0
#define ICON_FA_TORII_GATE "\xef\x9a\xa1"	// U+f6a1
#define ICON_FA_TRACTOR "\xef\x9c\xa2"	// U+f722
#define ICON_FA_TRADEMARK "\xef\x89\x9c"	// U+f25c
#define ICON_FA_TRAFFIC_LIGHT "\xef\x98\xb7"	// U+f637
#define ICON_FA_TRAILER "\xee\x81\x81"	// U+e041
#define ICON_FA_TRAIN "\xef\x88\xb8"	// U+f238
#define ICON_FA_TRAM "\xef\x9f\x9a"	// U+f7da
#define ICON_FA_TRANSGENDER "\xef\x88\xa4"	// U+f224
#define ICON_FA_TRANSGENDER_ALT "\xef\x88\xa5"	// U+f225
#define ICON_FA_TRASH "\xef\x87\xb8"	// U+f1f8
#define ICON_FA_TRASH_ALT "\xef\x8b\xad"	// U+f2ed
#define ICON_FA_TRASH_RESTORE "\xef\xa0\xa9"	// U+f829
#define ICON_FA_TRASH_RESTORE_ALT "\xef\xa0\xaa"	// U+f82a
#define ICON_FA_TREE "\xef\x86\xbb"	// U+f1bb
#define ICON_FA_TROPHY "\xef\x82\x91"	// U+f091
#define ICON_FA_TRUCK "\xef\x83\x91"	// U+f0d1
#define ICON_FA_TRUCK_LOADING "\xef\x93\x9e"	// U+f4de
#define ICON_FA_TRUCK_MONSTER "\xef\x98\xbb"	// U+f63b
#define ICON_FA_TRUCK_MOVING "\xef\x93\x9f"	// U+f4df
#define ICON_FA_TRUCK_PICKUP "\xef\x98\xbc"	// U+f63c
#define ICON_FA_TSHIRT "\xef\x95\x93"	// U+f553
#define ICON_FA_TTY "\xef\x87\xa4"	// U+f1e4
#define ICON_FA_TV "\xef\x89\xac"	// U+f26c
#define ICON_FA_UMBRELLA "\xef\x83\xa9"	// U+f0e9
#define ICON_FA_UMBRELLA_BEACH "\xef\x97\x8a"	// U+f5ca
#define ICON_FA_UNDERLINE "\xef\x83\x8d"	// U+f0cd
#define ICON_FA_UNDO "\xef\x83\xa2"	// U+f0e2
#define ICON_FA_UNDO_ALT "\xef\x8b\xaa"	// U+f2ea
#define ICON_FA_UNIVERSAL_ACCESS "\xef\x8a\x9a"	// U+f29a
#define ICON_FA_UNIVERSITY "\xef\x86\x9c"	// U+f19c
#define ICON_FA_UNLINK "\xef\x84\xa7"	// U+f127
#define ICON_FA_UNLOCK "\xef\x82\x9c"	// U+f09c
#define ICON_FA_UNLOCK_ALT "\xef\x84\xbe"	// U+f13e
#define ICON_FA_UPLOAD "\xef\x82\x93"	// U+f093
#define ICON_FA_USER "\xef\x80\x87"	// U+f007
#define ICON_FA_USER_ALT "\xef\x90\x86"	// U+f406
#define ICON_FA_USER_ALT_SLASH "\xef\x93\xba"	// U+f4fa
#define ICON_FA_USER_ASTRONAUT "\xef\x93\xbb"	// U+f4fb
#define ICON_FA_USER_CHECK "\xef\x93\xbc"	// U+f4fc
#define ICON_FA_USER_CIRCLE "\xef\x8a\xbd"	// U+f2bd
#define ICON_FA_USER_CLOCK "\xef\x93\xbd"	// U+f4fd
#define ICON_FA_USER_COG "\xef\x93\xbe"	// U+f4fe
#define ICON_FA_USER_EDIT "\xef\x93\xbf"	// U+f4ff
#define ICON_FA_USER_FRIENDS "\xef\x94\x80"	// U+f500
#define ICON_FA_USER_GRADUATE "\xef\x94\x81"	// U+f501
#define ICON_FA_USER_INJURED "\xef\x9c\xa8"	// U+f728
#define ICON_FA_USER_LOCK "\xef\x94\x82"	// U+f502
#define ICON_FA_USER_MD "\xef\x83\xb0"	// U+f0f0
#define ICON_FA_USER_MINUS "\xef\x94\x83"	// U+f503
#define ICON_FA_USER_NINJA "\xef\x94\x84"	// U+f504
#define ICON_FA_USER_NURSE "\xef\xa0\xaf"	// U+f82f
#define ICON_FA_USER_PLUS "\xef\x88\xb4"	// U+f234
#define ICON_FA_USER_SECRET "\xef\x88\x9b"	// U+f21b
#define ICON_FA_USER_SHIELD "\xef\x94\x85"	// U+f505
#define ICON_FA_USER_SLASH "\xef\x94\x86"	// U+f506
#define ICON_FA_USER_TAG "\xef\x94\x87"	// U+f507
#define ICON_FA_USER_TIE "\xef\x94\x88"	// U+f508
#define ICON_FA_USER_TIMES "\xef\x88\xb5"	// U+f235
#define ICON_FA_USERS "\xef\x83\x80"	// U+f0c0
#define ICON_FA_USERS_COG "\xef\x94\x89"	// U+f509
#define ICON_FA_USERS_SLASH "\xee\x81\xb3"	// U+e073
#define ICON_FA_UTENSIL_SPOON "\xef\x8b\xa5"	// U+f2e5
#define ICON_FA_UTENSILS "\xef\x8b\xa7"	// U+f2e7
#define ICON_FA_VECTOR_SQUARE "\xef\x97\x8b"	// U+f5cb
#define ICON_FA_VENUS "\xef\x88\xa1"	// U+f221
#define ICON_FA_VENUS_DOUBLE "\xef\x88\xa6"	// U+f226
#define ICON_FA_VENUS_MARS "\xef\x88\xa8"	// U+f228
#define ICON_FA_VEST "\xee\x82\x85"	// U+e085
#define ICON_FA_VEST_PATCHES "\xee\x82\x86"	// U+e086
#define ICON_FA_VIAL "\xef\x92\x92"	// U+f492
#define ICON_FA_VIALS "\xef\x92\x93"	// U+f493
#define ICON_FA_VIDEO "\xef\x80\xbd"	// U+f03d
#define ICON_FA_VIDEO_SLASH "\xef\x93\xa2"	// U+f4e2
#define ICON_FA_VIHARA "\xef\x9a\xa7"	// U+f6a7
#define ICON_FA_VIRUS "\xee\x81\xb4"	// U+e074
#define ICON_FA_VIRUS_SLASH "\xee\x81\xb5"	// U+e075
#define ICON_FA_VIRUSES "\xee\x81\xb6"	// U+e076
#define ICON_FA_VOICEMAIL "\xef\xa2\x97"	// U+f897
#define ICON_FA_VOLLEYBALL_BALL "\xef\x91\x9f"	// U+f45f
#define ICON_FA_VOLUME_DOWN "\xef\x80\xa7"	// U+f027
#define ICON_FA_VOLUME_MUTE "\xef\x9a\xa9"	// U+f6a9
#define ICON_FA_VOLUME_OFF "\xef\x80\xa6"	// U+f026
#define ICON_FA_VOLUME_UP "\xef\x80\xa8"	// U+f028
#define ICON_FA_VOTE_YEA "\xef\x9d\xb2"	// U+f772
#define ICON_FA_VR_CARDBOARD "\xef\x9c\xa9"	// U+f729
#define ICON_FA_WALKING "\xef\x95\x94"	// U+f554
#define ICON_FA_WALLET "\xef\x95\x95"	// U+f555
#define ICON_FA_WAREHOUSE "\xef\x92\x94"	// U+f494
#define ICON_FA_WATER "\xef\x9d\xb3"	// U+f773
#define ICON_FA_WAVE_SQUARE "\xef\xa0\xbe"	// U+f83e
#define ICON_FA_WEIGHT "\xef\x92\x96"	// U+f496
#define ICON_FA_WEIGHT_HANGING "\xef\x97\x8d"	// U+f5cd
#define ICON_FA_WHEELCHAIR "\xef\x86\x93"	// U+f193
#define ICON_FA_WIFI "\xef\x87\xab"	// U+f1eb
#define ICON_FA_WIND "\xef\x9c\xae"	// U+f72e
#define ICON_FA_WINDOW_CLOSE "\xef\x90\x90"	// U+f410
#define ICON_FA_WINDOW_MAXIMIZE "\xef\x8b\x90"	// U+f2d0
#define ICON_FA_WINDOW_MINIMIZE "\xef\x8b\x91"	// U+f2d1
#define ICON_FA_WINDOW_RESTORE "\xef\x8b\x92"	// U+f2d2
#define ICON_FA_WINE_BOTTLE "\xef\x9c\xaf"	// U+f72f
#define ICON_FA_WINE_GLASS "\xef\x93\xa3"	// U+f4e3
#define ICON_FA_WINE_GLASS_ALT "\xef\x97\x8e"	// U+f5ce
#define ICON_FA_WON_SIGN "\xef\x85\x99"	// U+f159
#define ICON_FA_WRENCH "\xef\x82\xad"	// U+f0ad
#define ICON_FA_X_RAY "\xef\x92\x97"	// U+f497
#define ICON_FA_YEN_SIGN "\xef\x85\x97"	// U+f157
#define ICON_FA_YIN_YANG "\xef\x9a\xad"	// U+f6ad

#pragma endregion

struct FontAwesome5Icon {
    const char* utf8_data;
    const char* name;
    unsigned int unicode;
};

static const FontAwesome5Icon FA5_ICONS[] = {
    #pragma region FontAwesome5Icon

    {ICON_FA_AD, "AD", 0xf641},
    {ICON_FA_ADDRESS_BOOK, "ADDRESS_BOOK", 0xf2b9},
    {ICON_FA_ADDRESS_CARD, "ADDRESS_CARD", 0xf2bb},
    {ICON_FA_ADJUST, "ADJUST", 0xf042},
    {ICON_FA_AIR_FRESHENER, "AIR_FRESHENER", 0xf5d0},
    {ICON_FA_ALIGN_CENTER, "ALIGN_CENTER", 0xf037},
    {ICON_FA_ALIGN_JUSTIFY, "ALIGN_JUSTIFY", 0xf039},
    {ICON_FA_ALIGN_LEFT, "ALIGN_LEFT", 0xf036},
    {ICON_FA_ALIGN_RIGHT, "ALIGN_RIGHT", 0xf038},
    {ICON_FA_ALLERGIES, "ALLERGIES", 0xf461},
    {ICON_FA_AMBULANCE, "AMBULANCE", 0xf0f9},
    {ICON_FA_AMERICAN_SIGN_LANGUAGE_INTERPRETING, "AMERICAN_SIGN_LANGUAGE_INTERPRETING", 0xf2a3},
    {ICON_FA_ANCHOR, "ANCHOR", 0xf13d},
    {ICON_FA_ANGLE_DOUBLE_DOWN, "ANGLE_DOUBLE_DOWN", 0xf103},
    {ICON_FA_ANGLE_DOUBLE_LEFT, "ANGLE_DOUBLE_LEFT", 0xf100},
    {ICON_FA_ANGLE_DOUBLE_RIGHT, "ANGLE_DOUBLE_RIGHT", 0xf101},
    {ICON_FA_ANGLE_DOUBLE_UP, "ANGLE_DOUBLE_UP", 0xf102},
    {ICON_FA_ANGLE_DOWN, "ANGLE_DOWN", 0xf107},
    {ICON_FA_ANGLE_LEFT, "ANGLE_LEFT", 0xf104},
    {ICON_FA_ANGLE_RIGHT, "ANGLE_RIGHT", 0xf105},
    {ICON_FA_ANGLE_UP, "ANGLE_UP", 0xf106},
    {ICON_FA_ANGRY, "ANGRY", 0xf556},
    {ICON_FA_ANKH, "ANKH", 0xf644},
    {ICON_FA_APPLE_ALT, "APPLE_ALT", 0xf5d1},
    {ICON_FA_ARCHIVE, "ARCHIVE", 0xf187},
    {ICON_FA_ARCHWAY, "ARCHWAY", 0xf557},
    {ICON_FA_ARROW_ALT_CIRCLE_DOWN, "ARROW_ALT_CIRCLE_DOWN", 0xf358},
    {ICON_FA_ARROW_ALT_CIRCLE_LEFT, "ARROW_ALT_CIRCLE_LEFT", 0xf359},
    {ICON_FA_ARROW_ALT_CIRCLE_RIGHT, "ARROW_ALT_CIRCLE_RIGHT", 0xf35a},
    {ICON_FA_ARROW_ALT_CIRCLE_UP, "ARROW_ALT_CIRCLE_UP", 0xf35b},
    {ICON_FA_ARROW_CIRCLE_DOWN, "ARROW_CIRCLE_DOWN", 0xf0ab},
    {ICON_FA_ARROW_CIRCLE_LEFT, "ARROW_CIRCLE_LEFT", 0xf0a8},
    {ICON_FA_ARROW_CIRCLE_RIGHT, "ARROW_CIRCLE_RIGHT", 0xf0a9},
    {ICON_FA_ARROW_CIRCLE_UP, "ARROW_CIRCLE_UP", 0xf0aa},
    {ICON_FA_ARROW_DOWN, "ARROW_DOWN", 0xf063},
    {ICON_FA_ARROW_LEFT, "ARROW_LEFT", 0xf060},
    {ICON_FA_ARROW_RIGHT, "ARROW_RIGHT", 0xf061},
    {ICON_FA_ARROW_UP, "ARROW_UP", 0xf062},
    {ICON_FA_ARROWS_ALT, "ARROWS_ALT", 0xf0b2},
    {ICON_FA_ARROWS_ALT_H, "ARROWS_ALT_H", 0xf337},
    {ICON_FA_ARROWS_ALT_V, "ARROWS_ALT_V", 0xf338},
    {ICON_FA_ASSISTIVE_LISTENING_SYSTEMS, "ASSISTIVE_LISTENING_SYSTEMS", 0xf2a2},
    {ICON_FA_ASTERISK, "ASTERISK", 0xf069},
    {ICON_FA_AT, "AT", 0xf1fa},
    {ICON_FA_ATLAS, "ATLAS", 0xf558},
    {ICON_FA_ATOM, "ATOM", 0xf5d2},
    {ICON_FA_AUDIO_DESCRIPTION, "AUDIO_DESCRIPTION", 0xf29e},
    {ICON_FA_AWARD, "AWARD", 0xf559},
    {ICON_FA_BABY, "BABY", 0xf77c},
    {ICON_FA_BABY_CARRIAGE, "BABY_CARRIAGE", 0xf77d},
    {ICON_FA_BACKSPACE, "BACKSPACE", 0xf55a},
    {ICON_FA_BACKWARD, "BACKWARD", 0xf04a},
    {ICON_FA_BACON, "BACON", 0xf7e5},
    {ICON_FA_BACTERIA, "BACTERIA", 0xe059},
    {ICON_FA_BACTERIUM, "BACTERIUM", 0xe05a},
    {ICON_FA_BAHAI, "BAHAI", 0xf666},
    {ICON_FA_BALANCE_SCALE, "BALANCE_SCALE", 0xf24e},
    {ICON_FA_BALANCE_SCALE_LEFT, "BALANCE_SCALE_LEFT", 0xf515},
    {ICON_FA_BALANCE_SCALE_RIGHT, "BALANCE_SCALE_RIGHT", 0xf516},
    {ICON_FA_BAN, "BAN", 0xf05e},
    {ICON_FA_BAND_AID, "BAND_AID", 0xf462},
    {ICON_FA_BARCODE, "BARCODE", 0xf02a},
    {ICON_FA_BARS, "BARS", 0xf0c9},
    {ICON_FA_BASEBALL_BALL, "BASEBALL_BALL", 0xf433},
    {ICON_FA_BASKETBALL_BALL, "BASKETBALL_BALL", 0xf434},
    {ICON_FA_BATH, "BATH", 0xf2cd},
    {ICON_FA_BATTERY_EMPTY, "BATTERY_EMPTY", 0xf244},
    {ICON_FA_BATTERY_FULL, "BATTERY_FULL", 0xf240},
    {ICON_FA_BATTERY_HALF, "BATTERY_HALF", 0xf242},
    {ICON_FA_BATTERY_QUARTER, "BATTERY_QUARTER", 0xf243},
    {ICON_FA_BATTERY_THREE_QUARTERS, "BATTERY_THREE_QUARTERS", 0xf241},
    {ICON_FA_BED, "BED", 0xf236},
    {ICON_FA_BEER, "BEER", 0xf0fc},
    {ICON_FA_BELL, "BELL", 0xf0f3},
    {ICON_FA_BELL_SLASH, "BELL_SLASH", 0xf1f6},
    {ICON_FA_BEZIER_CURVE, "BEZIER_CURVE", 0xf55b},
    {ICON_FA_BIBLE, "BIBLE", 0xf647},
    {ICON_FA_BICYCLE, "BICYCLE", 0xf206},
    {ICON_FA_BIKING, "BIKING", 0xf84a},
    {ICON_FA_BINOCULARS, "BINOCULARS", 0xf1e5},
    {ICON_FA_BIOHAZARD, "BIOHAZARD", 0xf780},
    {ICON_FA_BIRTHDAY_CAKE, "BIRTHDAY_CAKE", 0xf1fd},
    {ICON_FA_BLENDER, "BLENDER", 0xf517},
    {ICON_FA_BLENDER_PHONE, "BLENDER_PHONE", 0xf6b6},
    {ICON_FA_BLIND, "BLIND", 0xf29d},
    {ICON_FA_BLOG, "BLOG", 0xf781},
    {ICON_FA_BOLD, "BOLD", 0xf032},
    {ICON_FA_BOLT, "BOLT", 0xf0e7},
    {ICON_FA_BOMB, "BOMB", 0xf1e2},
    {ICON_FA_BONE, "BONE", 0xf5d7},
    {ICON_FA_BONG, "BONG", 0xf55c},
    {ICON_FA_BOOK, "BOOK", 0xf02d},
    {ICON_FA_BOOK_DEAD, "BOOK_DEAD", 0xf6b7},
    {ICON_FA_BOOK_MEDICAL, "BOOK_MEDICAL", 0xf7e6},
    {ICON_FA_BOOK_OPEN, "BOOK_OPEN", 0xf518},
    {ICON_FA_BOOK_READER, "BOOK_READER", 0xf5da},
    {ICON_FA_BOOKMARK, "BOOKMARK", 0xf02e},
    {ICON_FA_BORDER_ALL, "BORDER_ALL", 0xf84c},
    {ICON_FA_BORDER_NONE, "BORDER_NONE", 0xf850},
    {ICON_FA_BORDER_STYLE, "BORDER_STYLE", 0xf853},
    {ICON_FA_BOWLING_BALL, "BOWLING_BALL", 0xf436},
    {ICON_FA_BOX, "BOX", 0xf466},
    {ICON_FA_BOX_OPEN, "BOX_OPEN", 0xf49e},
    {ICON_FA_BOX_TISSUE, "BOX_TISSUE", 0xe05b},
    {ICON_FA_BOXES, "BOXES", 0xf468},
    {ICON_FA_BRAILLE, "BRAILLE", 0xf2a1},
    {ICON_FA_BRAIN, "BRAIN", 0xf5dc},
    {ICON_FA_BREAD_SLICE, "BREAD_SLICE", 0xf7ec},
    {ICON_FA_BRIEFCASE, "BRIEFCASE", 0xf0b1},
    {ICON_FA_BRIEFCASE_MEDICAL, "BRIEFCASE_MEDICAL", 0xf469},
    {ICON_FA_BROADCAST_TOWER, "BROADCAST_TOWER", 0xf519},
    {ICON_FA_BROOM, "BROOM", 0xf51a},
    {ICON_FA_BRUSH, "BRUSH", 0xf55d},
    {ICON_FA_BUG, "BUG", 0xf188},
    {ICON_FA_BUILDING, "BUILDING", 0xf1ad},
    {ICON_FA_BULLHORN, "BULLHORN", 0xf0a1},
    {ICON_FA_BULLSEYE, "BULLSEYE", 0xf140},
    {ICON_FA_BURN, "BURN", 0xf46a},
    {ICON_FA_BUS, "BUS", 0xf207},
    {ICON_FA_BUS_ALT, "BUS_ALT", 0xf55e},
    {ICON_FA_BUSINESS_TIME, "BUSINESS_TIME", 0xf64a},
    {ICON_FA_CALCULATOR, "CALCULATOR", 0xf1ec},
    {ICON_FA_CALENDAR, "CALENDAR", 0xf133},
    {ICON_FA_CALENDAR_ALT, "CALENDAR_ALT", 0xf073},
    {ICON_FA_CALENDAR_CHECK, "CALENDAR_CHECK", 0xf274},
    {ICON_FA_CALENDAR_DAY, "CALENDAR_DAY", 0xf783},
    {ICON_FA_CALENDAR_MINUS, "CALENDAR_MINUS", 0xf272},
    {ICON_FA_CALENDAR_PLUS, "CALENDAR_PLUS", 0xf271},
    {ICON_FA_CALENDAR_TIMES, "CALENDAR_TIMES", 0xf273},
    {ICON_FA_CALENDAR_WEEK, "CALENDAR_WEEK", 0xf784},
    {ICON_FA_CAMERA, "CAMERA", 0xf030},
    {ICON_FA_CAMERA_RETRO, "CAMERA_RETRO", 0xf083},
    {ICON_FA_CAMPGROUND, "CAMPGROUND", 0xf6bb},
    {ICON_FA_CANDY_CANE, "CANDY_CANE", 0xf786},
    {ICON_FA_CANNABIS, "CANNABIS", 0xf55f},
    {ICON_FA_CAPSULES, "CAPSULES", 0xf46b},
    {ICON_FA_CAR, "CAR", 0xf1b9},
    {ICON_FA_CAR_ALT, "CAR_ALT", 0xf5de},
    {ICON_FA_CAR_BATTERY, "CAR_BATTERY", 0xf5df},
    {ICON_FA_CAR_CRASH, "CAR_CRASH", 0xf5e1},
    {ICON_FA_CAR_SIDE, "CAR_SIDE", 0xf5e4},
    {ICON_FA_CARAVAN, "CARAVAN", 0xf8ff},
    {ICON_FA_CARET_DOWN, "CARET_DOWN", 0xf0d7},
    {ICON_FA_CARET_LEFT, "CARET_LEFT", 0xf0d9},
    {ICON_FA_CARET_RIGHT, "CARET_RIGHT", 0xf0da},
    {ICON_FA_CARET_SQUARE_DOWN, "CARET_SQUARE_DOWN", 0xf150},
    {ICON_FA_CARET_SQUARE_LEFT, "CARET_SQUARE_LEFT", 0xf191},
    {ICON_FA_CARET_SQUARE_RIGHT, "CARET_SQUARE_RIGHT", 0xf152},
    {ICON_FA_CARET_SQUARE_UP, "CARET_SQUARE_UP", 0xf151},
    {ICON_FA_CARET_UP, "CARET_UP", 0xf0d8},
    {ICON_FA_CARROT, "CARROT", 0xf787},
    {ICON_FA_CART_ARROW_DOWN, "CART_ARROW_DOWN", 0xf218},
    {ICON_FA_CART_PLUS, "CART_PLUS", 0xf217},
    {ICON_FA_CASH_REGISTER, "CASH_REGISTER", 0xf788},
    {ICON_FA_CAT, "CAT", 0xf6be},
    {ICON_FA_CERTIFICATE, "CERTIFICATE", 0xf0a3},
    {ICON_FA_CHAIR, "CHAIR", 0xf6c0},
    {ICON_FA_CHALKBOARD, "CHALKBOARD", 0xf51b},
    {ICON_FA_CHALKBOARD_TEACHER, "CHALKBOARD_TEACHER", 0xf51c},
    {ICON_FA_CHARGING_STATION, "CHARGING_STATION", 0xf5e7},
    {ICON_FA_CHART_AREA, "CHART_AREA", 0xf1fe},
    {ICON_FA_CHART_BAR, "CHART_BAR", 0xf080},
    {ICON_FA_CHART_LINE, "CHART_LINE", 0xf201},
    {ICON_FA_CHART_PIE, "CHART_PIE", 0xf200},
    {ICON_FA_CHECK, "CHECK", 0xf00c},
    {ICON_FA_CHECK_CIRCLE, "CHECK_CIRCLE", 0xf058},
    {ICON_FA_CHECK_DOUBLE, "CHECK_DOUBLE", 0xf560},
    {ICON_FA_CHECK_SQUARE, "CHECK_SQUARE", 0xf14a},
    {ICON_FA_CHEESE, "CHEESE", 0xf7ef},
    {ICON_FA_CHESS, "CHESS", 0xf439},
    {ICON_FA_CHESS_BISHOP, "CHESS_BISHOP", 0xf43a},
    {ICON_FA_CHESS_BOARD, "CHESS_BOARD", 0xf43c},
    {ICON_FA_CHESS_KING, "CHESS_KING", 0xf43f},
    {ICON_FA_CHESS_KNIGHT, "CHESS_KNIGHT", 0xf441},
    {ICON_FA_CHESS_PAWN, "CHESS_PAWN", 0xf443},
    {ICON_FA_CHESS_QUEEN, "CHESS_QUEEN", 0xf445},
    {ICON_FA_CHESS_ROOK, "CHESS_ROOK", 0xf447},
    {ICON_FA_CHEVRON_CIRCLE_DOWN, "CHEVRON_CIRCLE_DOWN", 0xf13a},
    {ICON_FA_CHEVRON_CIRCLE_LEFT, "CHEVRON_CIRCLE_LEFT", 0xf137},
    {ICON_FA_CHEVRON_CIRCLE_RIGHT, "CHEVRON_CIRCLE_RIGHT", 0xf138},
    {ICON_FA_CHEVRON_CIRCLE_UP, "CHEVRON_CIRCLE_UP", 0xf139},
    {ICON_FA_CHEVRON_DOWN, "CHEVRON_DOWN", 0xf078},
    {ICON_FA_CHEVRON_LEFT, "CHEVRON_LEFT", 0xf053},
    {ICON_FA_CHEVRON_RIGHT, "CHEVRON_RIGHT", 0xf054},
    {ICON_FA_CHEVRON_UP, "CHEVRON_UP", 0xf077},
    {ICON_FA_CHILD, "CHILD", 0xf1ae},
    {ICON_FA_CHURCH, "CHURCH", 0xf51d},
    {ICON_FA_CIRCLE, "CIRCLE", 0xf111},
    {ICON_FA_CIRCLE_NOTCH, "CIRCLE_NOTCH", 0xf1ce},
    {ICON_FA_CITY, "CITY", 0xf64f},
    {ICON_FA_CLINIC_MEDICAL, "CLINIC_MEDICAL", 0xf7f2},
    {ICON_FA_CLIPBOARD, "CLIPBOARD", 0xf328},
    {ICON_FA_CLIPBOARD_CHECK, "CLIPBOARD_CHECK", 0xf46c},
    {ICON_FA_CLIPBOARD_LIST, "CLIPBOARD_LIST", 0xf46d},
    {ICON_FA_CLOCK, "CLOCK", 0xf017},
    {ICON_FA_CLONE, "CLONE", 0xf24d},
    {ICON_FA_CLOSED_CAPTIONING, "CLOSED_CAPTIONING", 0xf20a},
    {ICON_FA_CLOUD, "CLOUD", 0xf0c2},
    {ICON_FA_CLOUD_DOWNLOAD_ALT, "CLOUD_DOWNLOAD_ALT", 0xf381},
    {ICON_FA_CLOUD_MEATBALL, "CLOUD_MEATBALL", 0xf73b},
    {ICON_FA_CLOUD_MOON, "CLOUD_MOON", 0xf6c3},
    {ICON_FA_CLOUD_MOON_RAIN, "CLOUD_MOON_RAIN", 0xf73c},
    {ICON_FA_CLOUD_RAIN, "CLOUD_RAIN", 0xf73d},
    {ICON_FA_CLOUD_SHOWERS_HEAVY, "CLOUD_SHOWERS_HEAVY", 0xf740},
    {ICON_FA_CLOUD_SUN, "CLOUD_SUN", 0xf6c4},
    {ICON_FA_CLOUD_SUN_RAIN, "CLOUD_SUN_RAIN", 0xf743},
    {ICON_FA_CLOUD_UPLOAD_ALT, "CLOUD_UPLOAD_ALT", 0xf382},
    {ICON_FA_COCKTAIL, "COCKTAIL", 0xf561},
    {ICON_FA_CODE, "CODE", 0xf121},
    {ICON_FA_CODE_BRANCH, "CODE_BRANCH", 0xf126},
    {ICON_FA_COFFEE, "COFFEE", 0xf0f4},
    {ICON_FA_COG, "COG", 0xf013},
    {ICON_FA_COGS, "COGS", 0xf085},
    {ICON_FA_COINS, "COINS", 0xf51e},
    {ICON_FA_COLUMNS, "COLUMNS", 0xf0db},
    {ICON_FA_COMMENT, "COMMENT", 0xf075},
    {ICON_FA_COMMENT_ALT, "COMMENT_ALT", 0xf27a},
    {ICON_FA_COMMENT_DOLLAR, "COMMENT_DOLLAR", 0xf651},
    {ICON_FA_COMMENT_DOTS, "COMMENT_DOTS", 0xf4ad},
    {ICON_FA_COMMENT_MEDICAL, "COMMENT_MEDICAL", 0xf7f5},
    {ICON_FA_COMMENT_SLASH, "COMMENT_SLASH", 0xf4b3},
    {ICON_FA_COMMENTS, "COMMENTS", 0xf086},
    {ICON_FA_COMMENTS_DOLLAR, "COMMENTS_DOLLAR", 0xf653},
    {ICON_FA_COMPACT_DISC, "COMPACT_DISC", 0xf51f},
    {ICON_FA_COMPASS, "COMPASS", 0xf14e},
    {ICON_FA_COMPRESS, "COMPRESS", 0xf066},
    {ICON_FA_COMPRESS_ALT, "COMPRESS_ALT", 0xf422},
    {ICON_FA_COMPRESS_ARROWS_ALT, "COMPRESS_ARROWS_ALT", 0xf78c},
    {ICON_FA_CONCIERGE_BELL, "CONCIERGE_BELL", 0xf562},
    {ICON_FA_COOKIE, "COOKIE", 0xf563},
    {ICON_FA_COOKIE_BITE, "COOKIE_BITE", 0xf564},
    {ICON_FA_COPY, "COPY", 0xf0c5},
    {ICON_FA_COPYRIGHT, "COPYRIGHT", 0xf1f9},
    {ICON_FA_COUCH, "COUCH", 0xf4b8},
    {ICON_FA_CREDIT_CARD, "CREDIT_CARD", 0xf09d},
    {ICON_FA_CROP, "CROP", 0xf125},
    {ICON_FA_CROP_ALT, "CROP_ALT", 0xf565},
    {ICON_FA_CROSS, "CROSS", 0xf654},
    {ICON_FA_CROSSHAIRS, "CROSSHAIRS", 0xf05b},
    {ICON_FA_CROW, "CROW", 0xf520},
    {ICON_FA_CROWN, "CROWN", 0xf521},
    {ICON_FA_CRUTCH, "CRUTCH", 0xf7f7},
    {ICON_FA_CUBE, "CUBE", 0xf1b2},
    {ICON_FA_CUBES, "CUBES", 0xf1b3},
    {ICON_FA_CUT, "CUT", 0xf0c4},
    {ICON_FA_DATABASE, "DATABASE", 0xf1c0},
    {ICON_FA_DEAF, "DEAF", 0xf2a4},
    {ICON_FA_DEMOCRAT, "DEMOCRAT", 0xf747},
    {ICON_FA_DESKTOP, "DESKTOP", 0xf108},
    {ICON_FA_DHARMACHAKRA, "DHARMACHAKRA", 0xf655},
    {ICON_FA_DIAGNOSES, "DIAGNOSES", 0xf470},
    {ICON_FA_DICE, "DICE", 0xf522},
    {ICON_FA_DICE_D20, "DICE_D20", 0xf6cf},
    {ICON_FA_DICE_D6, "DICE_D6", 0xf6d1},
    {ICON_FA_DICE_FIVE, "DICE_FIVE", 0xf523},
    {ICON_FA_DICE_FOUR, "DICE_FOUR", 0xf524},
    {ICON_FA_DICE_ONE, "DICE_ONE", 0xf525},
    {ICON_FA_DICE_SIX, "DICE_SIX", 0xf526},
    {ICON_FA_DICE_THREE, "DICE_THREE", 0xf527},
    {ICON_FA_DICE_TWO, "DICE_TWO", 0xf528},
    {ICON_FA_DIGITAL_TACHOGRAPH, "DIGITAL_TACHOGRAPH", 0xf566},
    {ICON_FA_DIRECTIONS, "DIRECTIONS", 0xf5eb},
    {ICON_FA_DISEASE, "DISEASE", 0xf7fa},
    {ICON_FA_DIVIDE, "DIVIDE", 0xf529},
    {ICON_FA_DIZZY, "DIZZY", 0xf567},
    {ICON_FA_DNA, "DNA", 0xf471},
    {ICON_FA_DOG, "DOG", 0xf6d3},
    {ICON_FA_DOLLAR_SIGN, "DOLLAR_SIGN", 0xf155},
    {ICON_FA_DOLLY, "DOLLY", 0xf472},
    {ICON_FA_DOLLY_FLATBED, "DOLLY_FLATBED", 0xf474},
    {ICON_FA_DONATE, "DONATE", 0xf4b9},
    {ICON_FA_DOOR_CLOSED, "DOOR_CLOSED", 0xf52a},
    {ICON_FA_DOOR_OPEN, "DOOR_OPEN", 0xf52b},
    {ICON_FA_DOT_CIRCLE, "DOT_CIRCLE", 0xf192},
    {ICON_FA_DOVE, "DOVE", 0xf4ba},
    {ICON_FA_DOWNLOAD, "DOWNLOAD", 0xf019},
    {ICON_FA_DRAFTING_COMPASS, "DRAFTING_COMPASS", 0xf568},
    {ICON_FA_DRAGON, "DRAGON", 0xf6d5},
    {ICON_FA_DRAW_POLYGON, "DRAW_POLYGON", 0xf5ee},
    {ICON_FA_DRUM, "DRUM", 0xf569},
    {ICON_FA_DRUM_STEELPAN, "DRUM_STEELPAN", 0xf56a},
    {ICON_FA_DRUMSTICK_BITE, "DRUMSTICK_BITE", 0xf6d7},
    {ICON_FA_DUMBBELL, "DUMBBELL", 0xf44b},
    {ICON_FA_DUMPSTER, "DUMPSTER", 0xf793},
    {ICON_FA_DUMPSTER_FIRE, "DUMPSTER_FIRE", 0xf794},
    {ICON_FA_DUNGEON, "DUNGEON", 0xf6d9},
    {ICON_FA_EDIT, "EDIT", 0xf044},
    {ICON_FA_EGG, "EGG", 0xf7fb},
    {ICON_FA_EJECT, "EJECT", 0xf052},
    {ICON_FA_ELLIPSIS_H, "ELLIPSIS_H", 0xf141},
    {ICON_FA_ELLIPSIS_V, "ELLIPSIS_V", 0xf142},
    {ICON_FA_ENVELOPE, "ENVELOPE", 0xf0e0},
    {ICON_FA_ENVELOPE_OPEN, "ENVELOPE_OPEN", 0xf2b6},
    {ICON_FA_ENVELOPE_OPEN_TEXT, "ENVELOPE_OPEN_TEXT", 0xf658},
    {ICON_FA_ENVELOPE_SQUARE, "ENVELOPE_SQUARE", 0xf199},
    {ICON_FA_EQUALS, "EQUALS", 0xf52c},
    {ICON_FA_ERASER, "ERASER", 0xf12d},
    {ICON_FA_ETHERNET, "ETHERNET", 0xf796},
    {ICON_FA_EURO_SIGN, "EURO_SIGN", 0xf153},
    {ICON_FA_EXCHANGE_ALT, "EXCHANGE_ALT", 0xf362},
    {ICON_FA_EXCLAMATION, "EXCLAMATION", 0xf12a},
    {ICON_FA_EXCLAMATION_CIRCLE, "EXCLAMATION_CIRCLE", 0xf06a},
    {ICON_FA_EXCLAMATION_TRIANGLE, "EXCLAMATION_TRIANGLE", 0xf071},
    {ICON_FA_EXPAND, "EXPAND", 0xf065},
    {ICON_FA_EXPAND_ALT, "EXPAND_ALT", 0xf424},
    {ICON_FA_EXPAND_ARROWS_ALT, "EXPAND_ARROWS_ALT", 0xf31e},
    {ICON_FA_EXTERNAL_LINK_ALT, "EXTERNAL_LINK_ALT", 0xf35d},
    {ICON_FA_EXTERNAL_LINK_SQUARE_ALT, "EXTERNAL_LINK_SQUARE_ALT", 0xf360},
    {ICON_FA_EYE, "EYE", 0xf06e},
    {ICON_FA_EYE_DROPPER, "EYE_DROPPER", 0xf1fb},
    {ICON_FA_EYE_SLASH, "EYE_SLASH", 0xf070},
    {ICON_FA_FAN, "FAN", 0xf863},
    {ICON_FA_FAST_BACKWARD, "FAST_BACKWARD", 0xf049},
    {ICON_FA_FAST_FORWARD, "FAST_FORWARD", 0xf050},
    {ICON_FA_FAUCET, "FAUCET", 0xe005},
    {ICON_FA_FAX, "FAX", 0xf1ac},
    {ICON_FA_FEATHER, "FEATHER", 0xf52d},
    {ICON_FA_FEATHER_ALT, "FEATHER_ALT", 0xf56b},
    {ICON_FA_FEMALE, "FEMALE", 0xf182},
    {ICON_FA_FIGHTER_JET, "FIGHTER_JET", 0xf0fb},
    {ICON_FA_FILE, "FILE", 0xf15b},
    {ICON_FA_FILE_ALT, "FILE_ALT", 0xf15c},
    {ICON_FA_FILE_ARCHIVE, "FILE_ARCHIVE", 0xf1c6},
    {ICON_FA_FILE_AUDIO, "FILE_AUDIO", 0xf1c7},
    {ICON_FA_FILE_CODE, "FILE_CODE", 0xf1c9},
    {ICON_FA_FILE_CONTRACT, "FILE_CONTRACT", 0xf56c},
    {ICON_FA_FILE_CSV, "FILE_CSV", 0xf6dd},
    {ICON_FA_FILE_DOWNLOAD, "FILE_DOWNLOAD", 0xf56d},
    {ICON_FA_FILE_EXCEL, "FILE_EXCEL", 0xf1c3},
    {ICON_FA_FILE_EXPORT, "FILE_EXPORT", 0xf56e},
    {ICON_FA_FILE_IMAGE, "FILE_IMAGE", 0xf1c5},
    {ICON_FA_FILE_IMPORT, "FILE_IMPORT", 0xf56f},
    {ICON_FA_FILE_INVOICE, "FILE_INVOICE", 0xf570},
    {ICON_FA_FILE_INVOICE_DOLLAR, "FILE_INVOICE_DOLLAR", 0xf571},
    {ICON_FA_FILE_MEDICAL, "FILE_MEDICAL", 0xf477},
    {ICON_FA_FILE_MEDICAL_ALT, "FILE_MEDICAL_ALT", 0xf478},
    {ICON_FA_FILE_PDF, "FILE_PDF", 0xf1c1},
    {ICON_FA_FILE_POWERPOINT, "FILE_POWERPOINT", 0xf1c4},
    {ICON_FA_FILE_PRESCRIPTION, "FILE_PRESCRIPTION", 0xf572},
    {ICON_FA_FILE_SIGNATURE, "FILE_SIGNATURE", 0xf573},
    {ICON_FA_FILE_UPLOAD, "FILE_UPLOAD", 0xf574},
    {ICON_FA_FILE_VIDEO, "FILE_VIDEO", 0xf1c8},
    {ICON_FA_FILE_WORD, "FILE_WORD", 0xf1c2},
    {ICON_FA_FILL, "FILL", 0xf575},
    {ICON_FA_FILL_DRIP, "FILL_DRIP", 0xf576},
    {ICON_FA_FILM, "FILM", 0xf008},
    {ICON_FA_FILTER, "FILTER", 0xf0b0},
    {ICON_FA_FINGERPRINT, "FINGERPRINT", 0xf577},
    {ICON_FA_FIRE, "FIRE", 0xf06d},
    {ICON_FA_FIRE_ALT, "FIRE_ALT", 0xf7e4},
    {ICON_FA_FIRE_EXTINGUISHER, "FIRE_EXTINGUISHER", 0xf134},
    {ICON_FA_FIRST_AID, "FIRST_AID", 0xf479},
    {ICON_FA_FISH, "FISH", 0xf578},
    {ICON_FA_FIST_RAISED, "FIST_RAISED", 0xf6de},
    {ICON_FA_FLAG, "FLAG", 0xf024},
    {ICON_FA_FLAG_CHECKERED, "FLAG_CHECKERED", 0xf11e},
    {ICON_FA_FLAG_USA, "FLAG_USA", 0xf74d},
    {ICON_FA_FLASK, "FLASK", 0xf0c3},
    {ICON_FA_FLUSHED, "FLUSHED", 0xf579},
    {ICON_FA_FOLDER, "FOLDER", 0xf07b},
    {ICON_FA_FOLDER_MINUS, "FOLDER_MINUS", 0xf65d},
    {ICON_FA_FOLDER_OPEN, "FOLDER_OPEN", 0xf07c},
    {ICON_FA_FOLDER_PLUS, "FOLDER_PLUS", 0xf65e},
    {ICON_FA_FONT, "FONT", 0xf031},
    {ICON_FA_FONT_AWESOME_LOGO_FULL, "FONT_AWESOME_LOGO_FULL", 0xf4e6},
    {ICON_FA_FOOTBALL_BALL, "FOOTBALL_BALL", 0xf44e},
    {ICON_FA_FORWARD, "FORWARD", 0xf04e},
    {ICON_FA_FROG, "FROG", 0xf52e},
    {ICON_FA_FROWN, "FROWN", 0xf119},
    {ICON_FA_FROWN_OPEN, "FROWN_OPEN", 0xf57a},
    {ICON_FA_FUNNEL_DOLLAR, "FUNNEL_DOLLAR", 0xf662},
    {ICON_FA_FUTBOL, "FUTBOL", 0xf1e3},
    {ICON_FA_GAMEPAD, "GAMEPAD", 0xf11b},
    {ICON_FA_GAS_PUMP, "GAS_PUMP", 0xf52f},
    {ICON_FA_GAVEL, "GAVEL", 0xf0e3},
    {ICON_FA_GEM, "GEM", 0xf3a5},
    {ICON_FA_GENDERLESS, "GENDERLESS", 0xf22d},
    {ICON_FA_GHOST, "GHOST", 0xf6e2},
    {ICON_FA_GIFT, "GIFT", 0xf06b},
    {ICON_FA_GIFTS, "GIFTS", 0xf79c},
    {ICON_FA_GLASS_CHEERS, "GLASS_CHEERS", 0xf79f},
    {ICON_FA_GLASS_MARTINI, "GLASS_MARTINI", 0xf000},
    {ICON_FA_GLASS_MARTINI_ALT, "GLASS_MARTINI_ALT", 0xf57b},
    {ICON_FA_GLASS_WHISKEY, "GLASS_WHISKEY", 0xf7a0},
    {ICON_FA_GLASSES, "GLASSES", 0xf530},
    {ICON_FA_GLOBE, "GLOBE", 0xf0ac},
    {ICON_FA_GLOBE_AFRICA, "GLOBE_AFRICA", 0xf57c},
    {ICON_FA_GLOBE_AMERICAS, "GLOBE_AMERICAS", 0xf57d},
    {ICON_FA_GLOBE_ASIA, "GLOBE_ASIA", 0xf57e},
    {ICON_FA_GLOBE_EUROPE, "GLOBE_EUROPE", 0xf7a2},
    {ICON_FA_GOLF_BALL, "GOLF_BALL", 0xf450},
    {ICON_FA_GOPURAM, "GOPURAM", 0xf664},
    {ICON_FA_GRADUATION_CAP, "GRADUATION_CAP", 0xf19d},
    {ICON_FA_GREATER_THAN, "GREATER_THAN", 0xf531},
    {ICON_FA_GREATER_THAN_EQUAL, "GREATER_THAN_EQUAL", 0xf532},
    {ICON_FA_GRIMACE, "GRIMACE", 0xf57f},
    {ICON_FA_GRIN, "GRIN", 0xf580},
    {ICON_FA_GRIN_ALT, "GRIN_ALT", 0xf581},
    {ICON_FA_GRIN_BEAM, "GRIN_BEAM", 0xf582},
    {ICON_FA_GRIN_BEAM_SWEAT, "GRIN_BEAM_SWEAT", 0xf583},
    {ICON_FA_GRIN_HEARTS, "GRIN_HEARTS", 0xf584},
    {ICON_FA_GRIN_SQUINT, "GRIN_SQUINT", 0xf585},
    {ICON_FA_GRIN_SQUINT_TEARS, "GRIN_SQUINT_TEARS", 0xf586},
    {ICON_FA_GRIN_STARS, "GRIN_STARS", 0xf587},
    {ICON_FA_GRIN_TEARS, "GRIN_TEARS", 0xf588},
    {ICON_FA_GRIN_TONGUE, "GRIN_TONGUE", 0xf589},
    {ICON_FA_GRIN_TONGUE_SQUINT, "GRIN_TONGUE_SQUINT", 0xf58a},
    {ICON_FA_GRIN_TONGUE_WINK, "GRIN_TONGUE_WINK", 0xf58b},
    {ICON_FA_GRIN_WINK, "GRIN_WINK", 0xf58c},
    {ICON_FA_GRIP_HORIZONTAL, "GRIP_HORIZONTAL", 0xf58d},
    {ICON_FA_GRIP_LINES, "GRIP_LINES", 0xf7a4},
    {ICON_FA_GRIP_LINES_VERTICAL, "GRIP_LINES_VERTICAL", 0xf7a5},
    {ICON_FA_GRIP_VERTICAL, "GRIP_VERTICAL", 0xf58e},
    {ICON_FA_GUITAR, "GUITAR", 0xf7a6},
    {ICON_FA_H_SQUARE, "H_SQUARE", 0xf0fd},
    {ICON_FA_HAMBURGER, "HAMBURGER", 0xf805},
    {ICON_FA_HAMMER, "HAMMER", 0xf6e3},
    {ICON_FA_HAMSA, "HAMSA", 0xf665},
    {ICON_FA_HAND_HOLDING, "HAND_HOLDING", 0xf4bd},
    {ICON_FA_HAND_HOLDING_HEART, "HAND_HOLDING_HEART", 0xf4be},
    {ICON_FA_HAND_HOLDING_MEDICAL, "HAND_HOLDING_MEDICAL", 0xe05c},
    {ICON_FA_HAND_HOLDING_USD, "HAND_HOLDING_USD", 0xf4c0},
    {ICON_FA_HAND_HOLDING_WATER, "HAND_HOLDING_WATER", 0xf4c1},
    {ICON_FA_HAND_LIZARD, "HAND_LIZARD", 0xf258},
    {ICON_FA_HAND_MIDDLE_FINGER, "HAND_MIDDLE_FINGER", 0xf806},
    {ICON_FA_HAND_PAPER, "HAND_PAPER", 0xf256},
    {ICON_FA_HAND_PEACE, "HAND_PEACE", 0xf25b},
    {ICON_FA_HAND_POINT_DOWN, "HAND_POINT_DOWN", 0xf0a7},
    {ICON_FA_HAND_POINT_LEFT, "HAND_POINT_LEFT", 0xf0a5},
    {ICON_FA_HAND_POINT_RIGHT, "HAND_POINT_RIGHT", 0xf0a4},
    {ICON_FA_HAND_POINT_UP, "HAND_POINT_UP", 0xf0a6},
    {ICON_FA_HAND_POINTER, "HAND_POINTER", 0xf25a},
    {ICON_FA_HAND_ROCK, "HAND_ROCK", 0xf255},
    {ICON_FA_HAND_SCISSORS, "HAND_SCISSORS", 0xf257},
    {ICON_FA_HAND_SPARKLES, "HAND_SPARKLES", 0xe05d},
    {ICON_FA_HAND_SPOCK, "HAND_SPOCK", 0xf259},
    {ICON_FA_HANDS, "HANDS", 0xf4c2},
    {ICON_FA_HANDS_HELPING, "HANDS_HELPING", 0xf4c4},
    {ICON_FA_HANDS_WASH, "HANDS_WASH", 0xe05e},
    {ICON_FA_HANDSHAKE, "HANDSHAKE", 0xf2b5},
    {ICON_FA_HANDSHAKE_ALT_SLASH, "HANDSHAKE_ALT_SLASH", 0xe05f},
    {ICON_FA_HANDSHAKE_SLASH, "HANDSHAKE_SLASH", 0xe060},
    {ICON_FA_HANUKIAH, "HANUKIAH", 0xf6e6},
    {ICON_FA_HARD_HAT, "HARD_HAT", 0xf807},
    {ICON_FA_HASHTAG, "HASHTAG", 0xf292},
    {ICON_FA_HAT_COWBOY, "HAT_COWBOY", 0xf8c0},
    {ICON_FA_HAT_COWBOY_SIDE, "HAT_COWBOY_SIDE", 0xf8c1},
    {ICON_FA_HAT_WIZARD, "HAT_WIZARD", 0xf6e8},
    {ICON_FA_HDD, "HDD", 0xf0a0},
    {ICON_FA_HEAD_SIDE_COUGH, "HEAD_SIDE_COUGH", 0xe061},
    {ICON_FA_HEAD_SIDE_COUGH_SLASH, "HEAD_SIDE_COUGH_SLASH", 0xe062},
    {ICON_FA_HEAD_SIDE_MASK, "HEAD_SIDE_MASK", 0xe063},
    {ICON_FA_HEAD_SIDE_VIRUS, "HEAD_SIDE_VIRUS", 0xe064},
    {ICON_FA_HEADING, "HEADING", 0xf1dc},
    {ICON_FA_HEADPHONES, "HEADPHONES", 0xf025},
    {ICON_FA_HEADPHONES_ALT, "HEADPHONES_ALT", 0xf58f},
    {ICON_FA_HEADSET, "HEADSET", 0xf590},
    {ICON_FA_HEART, "HEART", 0xf004},
    {ICON_FA_HEART_BROKEN, "HEART_BROKEN", 0xf7a9},
    {ICON_FA_HEARTBEAT, "HEARTBEAT", 0xf21e},
    {ICON_FA_HELICOPTER, "HELICOPTER", 0xf533},
    {ICON_FA_HIGHLIGHTER, "HIGHLIGHTER", 0xf591},
    {ICON_FA_HIKING, "HIKING", 0xf6ec},
    {ICON_FA_HIPPO, "HIPPO", 0xf6ed},
    {ICON_FA_HISTORY, "HISTORY", 0xf1da},
    {ICON_FA_HOCKEY_PUCK, "HOCKEY_PUCK", 0xf453},
    {ICON_FA_HOLLY_BERRY, "HOLLY_BERRY", 0xf7aa},
    {ICON_FA_HOME, "HOME", 0xf015},
    {ICON_FA_HORSE, "HORSE", 0xf6f0},
    {ICON_FA_HORSE_HEAD, "HORSE_HEAD", 0xf7ab},
    {ICON_FA_HOSPITAL, "HOSPITAL", 0xf0f8},
    {ICON_FA_HOSPITAL_ALT, "HOSPITAL_ALT", 0xf47d},
    {ICON_FA_HOSPITAL_SYMBOL, "HOSPITAL_SYMBOL", 0xf47e},
    {ICON_FA_HOSPITAL_USER, "HOSPITAL_USER", 0xf80d},
    {ICON_FA_HOT_TUB, "HOT_TUB", 0xf593},
    {ICON_FA_HOTDOG, "HOTDOG", 0xf80f},
    {ICON_FA_HOTEL, "HOTEL", 0xf594},
    {ICON_FA_HOURGLASS, "HOURGLASS", 0xf254},
    {ICON_FA_HOURGLASS_END, "HOURGLASS_END", 0xf253},
    {ICON_FA_HOURGLASS_HALF, "HOURGLASS_HALF", 0xf252},
    {ICON_FA_HOURGLASS_START, "HOURGLASS_START", 0xf251},
    {ICON_FA_HOUSE_DAMAGE, "HOUSE_DAMAGE", 0xf6f1},
    {ICON_FA_HOUSE_USER, "HOUSE_USER", 0xe065},
    {ICON_FA_HRYVNIA, "HRYVNIA", 0xf6f2},
    {ICON_FA_I_CURSOR, "I_CURSOR", 0xf246},
    {ICON_FA_ICE_CREAM, "ICE_CREAM", 0xf810},
    {ICON_FA_ICICLES, "ICICLES", 0xf7ad},
    {ICON_FA_ICONS, "ICONS", 0xf86d},
    {ICON_FA_ID_BADGE, "ID_BADGE", 0xf2c1},
    {ICON_FA_ID_CARD, "ID_CARD", 0xf2c2},
    {ICON_FA_ID_CARD_ALT, "ID_CARD_ALT", 0xf47f},
    {ICON_FA_IGLOO, "IGLOO", 0xf7ae},
    {ICON_FA_IMAGE, "IMAGE", 0xf03e},
    {ICON_FA_IMAGES, "IMAGES", 0xf302},
    {ICON_FA_INBOX, "INBOX", 0xf01c},
    {ICON_FA_INDENT, "INDENT", 0xf03c},
    {ICON_FA_INDUSTRY, "INDUSTRY", 0xf275},
    {ICON_FA_INFINITY, "INFINITY", 0xf534},
    {ICON_FA_INFO, "INFO", 0xf129},
    {ICON_FA_INFO_CIRCLE, "INFO_CIRCLE", 0xf05a},
    {ICON_FA_ITALIC, "ITALIC", 0xf033},
    {ICON_FA_JEDI, "JEDI", 0xf669},
    {ICON_FA_JOINT, "JOINT", 0xf595},
    {ICON_FA_JOURNAL_WHILLS, "JOURNAL_WHILLS", 0xf66a},
    {ICON_FA_KAABA, "KAABA", 0xf66b},
    {ICON_FA_KEY, "KEY", 0xf084},
    {ICON_FA_KEYBOARD, "KEYBOARD", 0xf11c},
    {ICON_FA_KHANDA, "KHANDA", 0xf66d},
    {ICON_FA_KISS, "KISS", 0xf596},
    {ICON_FA_KISS_BEAM, "KISS_BEAM", 0xf597},
    {ICON_FA_KISS_WINK_HEART, "KISS_WINK_HEART", 0xf598},
    {ICON_FA_KIWI_BIRD, "KIWI_BIRD", 0xf535},
    {ICON_FA_LANDMARK, "LANDMARK", 0xf66f},
    {ICON_FA_LANGUAGE, "LANGUAGE", 0xf1ab},
    {ICON_FA_LAPTOP, "LAPTOP", 0xf109},
    {ICON_FA_LAPTOP_CODE, "LAPTOP_CODE", 0xf5fc},
    {ICON_FA_LAPTOP_HOUSE, "LAPTOP_HOUSE", 0xe066},
    {ICON_FA_LAPTOP_MEDICAL, "LAPTOP_MEDICAL", 0xf812},
    {ICON_FA_LAUGH, "LAUGH", 0xf599},
    {ICON_FA_LAUGH_BEAM, "LAUGH_BEAM", 0xf59a},
    {ICON_FA_LAUGH_SQUINT, "LAUGH_SQUINT", 0xf59b},
    {ICON_FA_LAUGH_WINK, "LAUGH_WINK", 0xf59c},
    {ICON_FA_LAYER_GROUP, "LAYER_GROUP", 0xf5fd},
    {ICON_FA_LEAF, "LEAF", 0xf06c},
    {ICON_FA_LEMON, "LEMON", 0xf094},
    {ICON_FA_LESS_THAN, "LESS_THAN", 0xf536},
    {ICON_FA_LESS_THAN_EQUAL, "LESS_THAN_EQUAL", 0xf537},
    {ICON_FA_LEVEL_DOWN_ALT, "LEVEL_DOWN_ALT", 0xf3be},
    {ICON_FA_LEVEL_UP_ALT, "LEVEL_UP_ALT", 0xf3bf},
    {ICON_FA_LIFE_RING, "LIFE_RING", 0xf1cd},
    {ICON_FA_LIGHTBULB, "LIGHTBULB", 0xf0eb},
    {ICON_FA_LINK, "LINK", 0xf0c1},
    {ICON_FA_LIRA_SIGN, "LIRA_SIGN", 0xf195},
    {ICON_FA_LIST, "LIST", 0xf03a},
    {ICON_FA_LIST_ALT, "LIST_ALT", 0xf022},
    {ICON_FA_LIST_OL, "LIST_OL", 0xf0cb},
    {ICON_FA_LIST_UL, "LIST_UL", 0xf0ca},
    {ICON_FA_LOCATION_ARROW, "LOCATION_ARROW", 0xf124},
    {ICON_FA_LOCK, "LOCK", 0xf023},
    {ICON_FA_LOCK_OPEN, "LOCK_OPEN", 0xf3c1},
    {ICON_FA_LONG_ARROW_ALT_DOWN, "LONG_ARROW_ALT_DOWN", 0xf309},
    {ICON_FA_LONG_ARROW_ALT_LEFT, "LONG_ARROW_ALT_LEFT", 0xf30a},
    {ICON_FA_LONG_ARROW_ALT_RIGHT, "LONG_ARROW_ALT_RIGHT", 0xf30b},
    {ICON_FA_LONG_ARROW_ALT_UP, "LONG_ARROW_ALT_UP", 0xf30c},
    {ICON_FA_LOW_VISION, "LOW_VISION", 0xf2a8},
    {ICON_FA_LUGGAGE_CART, "LUGGAGE_CART", 0xf59d},
    {ICON_FA_LUNGS, "LUNGS", 0xf604},
    {ICON_FA_LUNGS_VIRUS, "LUNGS_VIRUS", 0xe067},
    {ICON_FA_MAGIC, "MAGIC", 0xf0d0},
    {ICON_FA_MAGNET, "MAGNET", 0xf076},
    {ICON_FA_MAIL_BULK, "MAIL_BULK", 0xf674},
    {ICON_FA_MALE, "MALE", 0xf183},
    {ICON_FA_MAP, "MAP", 0xf279},
    {ICON_FA_MAP_MARKED, "MAP_MARKED", 0xf59f},
    {ICON_FA_MAP_MARKED_ALT, "MAP_MARKED_ALT", 0xf5a0},
    {ICON_FA_MAP_MARKER, "MAP_MARKER", 0xf041},
    {ICON_FA_MAP_MARKER_ALT, "MAP_MARKER_ALT", 0xf3c5},
    {ICON_FA_MAP_PIN, "MAP_PIN", 0xf276},
    {ICON_FA_MAP_SIGNS, "MAP_SIGNS", 0xf277},
    {ICON_FA_MARKER, "MARKER", 0xf5a1},
    {ICON_FA_MARS, "MARS", 0xf222},
    {ICON_FA_MARS_DOUBLE, "MARS_DOUBLE", 0xf227},
    {ICON_FA_MARS_STROKE, "MARS_STROKE", 0xf229},
    {ICON_FA_MARS_STROKE_H, "MARS_STROKE_H", 0xf22b},
    {ICON_FA_MARS_STROKE_V, "MARS_STROKE_V", 0xf22a},
    {ICON_FA_MASK, "MASK", 0xf6fa},
    {ICON_FA_MEDAL, "MEDAL", 0xf5a2},
    {ICON_FA_MEDKIT, "MEDKIT", 0xf0fa},
    {ICON_FA_MEH, "MEH", 0xf11a},
    {ICON_FA_MEH_BLANK, "MEH_BLANK", 0xf5a4},
    {ICON_FA_MEH_ROLLING_EYES, "MEH_ROLLING_EYES", 0xf5a5},
    {ICON_FA_MEMORY, "MEMORY", 0xf538},
    {ICON_FA_MENORAH, "MENORAH", 0xf676},
    {ICON_FA_MERCURY, "MERCURY", 0xf223},
    {ICON_FA_METEOR, "METEOR", 0xf753},
    {ICON_FA_MICROCHIP, "MICROCHIP", 0xf2db},
    {ICON_FA_MICROPHONE, "MICROPHONE", 0xf130},
    {ICON_FA_MICROPHONE_ALT, "MICROPHONE_ALT", 0xf3c9},
    {ICON_FA_MICROPHONE_ALT_SLASH, "MICROPHONE_ALT_SLASH", 0xf539},
    {ICON_FA_MICROPHONE_SLASH, "MICROPHONE_SLASH", 0xf131},
    {ICON_FA_MICROSCOPE, "MICROSCOPE", 0xf610},
    {ICON_FA_MINUS, "MINUS", 0xf068},
    {ICON_FA_MINUS_CIRCLE, "MINUS_CIRCLE", 0xf056},
    {ICON_FA_MINUS_SQUARE, "MINUS_SQUARE", 0xf146},
    {ICON_FA_MITTEN, "MITTEN", 0xf7b5},
    {ICON_FA_MOBILE, "MOBILE", 0xf10b},
    {ICON_FA_MOBILE_ALT, "MOBILE_ALT", 0xf3cd},
    {ICON_FA_MONEY_BILL, "MONEY_BILL", 0xf0d6},
    {ICON_FA_MONEY_BILL_ALT, "MONEY_BILL_ALT", 0xf3d1},
    {ICON_FA_MONEY_BILL_WAVE, "MONEY_BILL_WAVE", 0xf53a},
    {ICON_FA_MONEY_BILL_WAVE_ALT, "MONEY_BILL_WAVE_ALT", 0xf53b},
    {ICON_FA_MONEY_CHECK, "MONEY_CHECK", 0xf53c},
    {ICON_FA_MONEY_CHECK_ALT, "MONEY_CHECK_ALT", 0xf53d},
    {ICON_FA_MONUMENT, "MONUMENT", 0xf5a6},
    {ICON_FA_MOON, "MOON", 0xf186},
    {ICON_FA_MORTAR_PESTLE, "MORTAR_PESTLE", 0xf5a7},
    {ICON_FA_MOSQUE, "MOSQUE", 0xf678},
    {ICON_FA_MOTORCYCLE, "MOTORCYCLE", 0xf21c},
    {ICON_FA_MOUNTAIN, "MOUNTAIN", 0xf6fc},
    {ICON_FA_MOUSE, "MOUSE", 0xf8cc},
    {ICON_FA_MOUSE_POINTER, "MOUSE_POINTER", 0xf245},
    {ICON_FA_MUG_HOT, "MUG_HOT", 0xf7b6},
    {ICON_FA_MUSIC, "MUSIC", 0xf001},
    {ICON_FA_NETWORK_WIRED, "NETWORK_WIRED", 0xf6ff},
    {ICON_FA_NEUTER, "NEUTER", 0xf22c},
    {ICON_FA_NEWSPAPER, "NEWSPAPER", 0xf1ea},
    {ICON_FA_NOT_EQUAL, "NOT_EQUAL", 0xf53e},
    {ICON_FA_NOTES_MEDICAL, "NOTES_MEDICAL", 0xf481},
    {ICON_FA_OBJECT_GROUP, "OBJECT_GROUP", 0xf247},
    {ICON_FA_OBJECT_UNGROUP, "OBJECT_UNGROUP", 0xf248},
    {ICON_FA_OIL_CAN, "OIL_CAN", 0xf613},
    {ICON_FA_OM, "OM", 0xf679},
    {ICON_FA_OTTER, "OTTER", 0xf700},
    {ICON_FA_OUTDENT, "OUTDENT", 0xf03b},
    {ICON_FA_PAGER, "PAGER", 0xf815},
    {ICON_FA_PAINT_BRUSH, "PAINT_BRUSH", 0xf1fc},
    {ICON_FA_PAINT_ROLLER, "PAINT_ROLLER", 0xf5aa},
    {ICON_FA_PALETTE, "PALETTE", 0xf53f},
    {ICON_FA_PALLET, "PALLET", 0xf482},
    {ICON_FA_PAPER_PLANE, "PAPER_PLANE", 0xf1d8},
    {ICON_FA_PAPERCLIP, "PAPERCLIP", 0xf0c6},
    {ICON_FA_PARACHUTE_BOX, "PARACHUTE_BOX", 0xf4cd},
    {ICON_FA_PARAGRAPH, "PARAGRAPH", 0xf1dd},
    {ICON_FA_PARKING, "PARKING", 0xf540},
    {ICON_FA_PASSPORT, "PASSPORT", 0xf5ab},
    {ICON_FA_PASTAFARIANISM, "PASTAFARIANISM", 0xf67b},
    {ICON_FA_PASTE, "PASTE", 0xf0ea},
    {ICON_FA_PAUSE, "PAUSE", 0xf04c},
    {ICON_FA_PAUSE_CIRCLE, "PAUSE_CIRCLE", 0xf28b},
    {ICON_FA_PAW, "PAW", 0xf1b0},
    {ICON_FA_PEACE, "PEACE", 0xf67c},
    {ICON_FA_PEN, "PEN", 0xf304},
    {ICON_FA_PEN_ALT, "PEN_ALT", 0xf305},
    {ICON_FA_PEN_FANCY, "PEN_FANCY", 0xf5ac},
    {ICON_FA_PEN_NIB, "PEN_NIB", 0xf5ad},
    {ICON_FA_PEN_SQUARE, "PEN_SQUARE", 0xf14b},
    {ICON_FA_PENCIL_ALT, "PENCIL_ALT", 0xf303},
    {ICON_FA_PENCIL_RULER, "PENCIL_RULER", 0xf5ae},
    {ICON_FA_PEOPLE_ARROWS, "PEOPLE_ARROWS", 0xe068},
    {ICON_FA_PEOPLE_CARRY, "PEOPLE_CARRY", 0xf4ce},
    {ICON_FA_PEPPER_HOT, "PEPPER_HOT", 0xf816},
    {ICON_FA_PERCENT, "PERCENT", 0xf295},
    {ICON_FA_PERCENTAGE, "PERCENTAGE", 0xf541},
    {ICON_FA_PERSON_BOOTH, "PERSON_BOOTH", 0xf756},
    {ICON_FA_PHONE, "PHONE", 0xf095},
    {ICON_FA_PHONE_ALT, "PHONE_ALT", 0xf879},
    {ICON_FA_PHONE_SLASH, "PHONE_SLASH", 0xf3dd},
    {ICON_FA_PHONE_SQUARE, "PHONE_SQUARE", 0xf098},
    {ICON_FA_PHONE_SQUARE_ALT, "PHONE_SQUARE_ALT", 0xf87b},
    {ICON_FA_PHONE_VOLUME, "PHONE_VOLUME", 0xf2a0},
    {ICON_FA_PHOTO_VIDEO, "PHOTO_VIDEO", 0xf87c},
    {ICON_FA_PIGGY_BANK, "PIGGY_BANK", 0xf4d3},
    {ICON_FA_PILLS, "PILLS", 0xf484},
    {ICON_FA_PIZZA_SLICE, "PIZZA_SLICE", 0xf818},
    {ICON_FA_PLACE_OF_WORSHIP, "PLACE_OF_WORSHIP", 0xf67f},
    {ICON_FA_PLANE, "PLANE", 0xf072},
    {ICON_FA_PLANE_ARRIVAL, "PLANE_ARRIVAL", 0xf5af},
    {ICON_FA_PLANE_DEPARTURE, "PLANE_DEPARTURE", 0xf5b0},
    {ICON_FA_PLANE_SLASH, "PLANE_SLASH", 0xe069},
    {ICON_FA_PLAY, "PLAY", 0xf04b},
    {ICON_FA_PLAY_CIRCLE, "PLAY_CIRCLE", 0xf144},
    {ICON_FA_PLUG, "PLUG", 0xf1e6},
    {ICON_FA_PLUS, "PLUS", 0xf067},
    {ICON_FA_PLUS_CIRCLE, "PLUS_CIRCLE", 0xf055},
    {ICON_FA_PLUS_SQUARE, "PLUS_SQUARE", 0xf0fe},
    {ICON_FA_PODCAST, "PODCAST", 0xf2ce},
    {ICON_FA_POLL, "POLL", 0xf681},
    {ICON_FA_POLL_H, "POLL_H", 0xf682},
    {ICON_FA_POO, "POO", 0xf2fe},
    {ICON_FA_POO_STORM, "POO_STORM", 0xf75a},
    {ICON_FA_POOP, "POOP", 0xf619},
    {ICON_FA_PORTRAIT, "PORTRAIT", 0xf3e0},
    {ICON_FA_POUND_SIGN, "POUND_SIGN", 0xf154},
    {ICON_FA_POWER_OFF, "POWER_OFF", 0xf011},
    {ICON_FA_PRAY, "PRAY", 0xf683},
    {ICON_FA_PRAYING_HANDS, "PRAYING_HANDS", 0xf684},
    {ICON_FA_PRESCRIPTION, "PRESCRIPTION", 0xf5b1},
    {ICON_FA_PRESCRIPTION_BOTTLE, "PRESCRIPTION_BOTTLE", 0xf485},
    {ICON_FA_PRESCRIPTION_BOTTLE_ALT, "PRESCRIPTION_BOTTLE_ALT", 0xf486},
    {ICON_FA_PRINT, "PRINT", 0xf02f},
    {ICON_FA_PROCEDURES, "PROCEDURES", 0xf487},
    {ICON_FA_PROJECT_DIAGRAM, "PROJECT_DIAGRAM", 0xf542},
    {ICON_FA_PUMP_MEDICAL, "PUMP_MEDICAL", 0xe06a},
    {ICON_FA_PUMP_SOAP, "PUMP_SOAP", 0xe06b},
    {ICON_FA_PUZZLE_PIECE, "PUZZLE_PIECE", 0xf12e},
    {ICON_FA_QRCODE, "QRCODE", 0xf029},
    {ICON_FA_QUESTION, "QUESTION", 0xf128},
    {ICON_FA_QUESTION_CIRCLE, "QUESTION_CIRCLE", 0xf059},
    {ICON_FA_QUIDDITCH, "QUIDDITCH", 0xf458},
    {ICON_FA_QUOTE_LEFT, "QUOTE_LEFT", 0xf10d},
    {ICON_FA_QUOTE_RIGHT, "QUOTE_RIGHT", 0xf10e},
    {ICON_FA_QURAN, "QURAN", 0xf687},
    {ICON_FA_RADIATION, "RADIATION", 0xf7b9},
    {ICON_FA_RADIATION_ALT, "RADIATION_ALT", 0xf7ba},
    {ICON_FA_RAINBOW, "RAINBOW", 0xf75b},
    {ICON_FA_RANDOM, "RANDOM", 0xf074},
    {ICON_FA_RECEIPT, "RECEIPT", 0xf543},
    {ICON_FA_RECORD_VINYL, "RECORD_VINYL", 0xf8d9},
    {ICON_FA_RECYCLE, "RECYCLE", 0xf1b8},
    {ICON_FA_REDO, "REDO", 0xf01e},
    {ICON_FA_REDO_ALT, "REDO_ALT", 0xf2f9},
    {ICON_FA_REGISTERED, "REGISTERED", 0xf25d},
    {ICON_FA_REMOVE_FORMAT, "REMOVE_FORMAT", 0xf87d},
    {ICON_FA_REPLY, "REPLY", 0xf3e5},
    {ICON_FA_REPLY_ALL, "REPLY_ALL", 0xf122},
    {ICON_FA_REPUBLICAN, "REPUBLICAN", 0xf75e},
    {ICON_FA_RESTROOM, "RESTROOM", 0xf7bd},
    {ICON_FA_RETWEET, "RETWEET", 0xf079},
    {ICON_FA_RIBBON, "RIBBON", 0xf4d6},
    {ICON_FA_RING, "RING", 0xf70b},
    {ICON_FA_ROAD, "ROAD", 0xf018},
    {ICON_FA_ROBOT, "ROBOT", 0xf544},
    {ICON_FA_ROCKET, "ROCKET", 0xf135},
    {ICON_FA_ROUTE, "ROUTE", 0xf4d7},
    {ICON_FA_RSS, "RSS", 0xf09e},
    {ICON_FA_RSS_SQUARE, "RSS_SQUARE", 0xf143},
    {ICON_FA_RUBLE_SIGN, "RUBLE_SIGN", 0xf158},
    {ICON_FA_RULER, "RULER", 0xf545},
    {ICON_FA_RULER_COMBINED, "RULER_COMBINED", 0xf546},
    {ICON_FA_RULER_HORIZONTAL, "RULER_HORIZONTAL", 0xf547},
    {ICON_FA_RULER_VERTICAL, "RULER_VERTICAL", 0xf548},
    {ICON_FA_RUNNING, "RUNNING", 0xf70c},
    {ICON_FA_RUPEE_SIGN, "RUPEE_SIGN", 0xf156},
    {ICON_FA_SAD_CRY, "SAD_CRY", 0xf5b3},
    {ICON_FA_SAD_TEAR, "SAD_TEAR", 0xf5b4},
    {ICON_FA_SATELLITE, "SATELLITE", 0xf7bf},
    {ICON_FA_SATELLITE_DISH, "SATELLITE_DISH", 0xf7c0},
    {ICON_FA_SAVE, "SAVE", 0xf0c7},
    {ICON_FA_SCHOOL, "SCHOOL", 0xf549},
    {ICON_FA_SCREWDRIVER, "SCREWDRIVER", 0xf54a},
    {ICON_FA_SCROLL, "SCROLL", 0xf70e},
    {ICON_FA_SD_CARD, "SD_CARD", 0xf7c2},
    {ICON_FA_SEARCH, "SEARCH", 0xf002},
    {ICON_FA_SEARCH_DOLLAR, "SEARCH_DOLLAR", 0xf688},
    {ICON_FA_SEARCH_LOCATION, "SEARCH_LOCATION", 0xf689},
    {ICON_FA_SEARCH_MINUS, "SEARCH_MINUS", 0xf010},
    {ICON_FA_SEARCH_PLUS, "SEARCH_PLUS", 0xf00e},
    {ICON_FA_SEEDLING, "SEEDLING", 0xf4d8},
    {ICON_FA_SERVER, "SERVER", 0xf233},
    {ICON_FA_SHAPES, "SHAPES", 0xf61f},
    {ICON_FA_SHARE, "SHARE", 0xf064},
    {ICON_FA_SHARE_ALT, "SHARE_ALT", 0xf1e0},
    {ICON_FA_SHARE_ALT_SQUARE, "SHARE_ALT_SQUARE", 0xf1e1},
    {ICON_FA_SHARE_SQUARE, "SHARE_SQUARE", 0xf14d},
    {ICON_FA_SHEKEL_SIGN, "SHEKEL_SIGN", 0xf20b},
    {ICON_FA_SHIELD_ALT, "SHIELD_ALT", 0xf3ed},
    {ICON_FA_SHIELD_VIRUS, "SHIELD_VIRUS", 0xe06c},
    {ICON_FA_SHIP, "SHIP", 0xf21a},
    {ICON_FA_SHIPPING_FAST, "SHIPPING_FAST", 0xf48b},
    {ICON_FA_SHOE_PRINTS, "SHOE_PRINTS", 0xf54b},
    {ICON_FA_SHOPPING_BAG, "SHOPPING_BAG", 0xf290},
    {ICON_FA_SHOPPING_BASKET, "SHOPPING_BASKET", 0xf291},
    {ICON_FA_SHOPPING_CART, "SHOPPING_CART", 0xf07a},
    {ICON_FA_SHOWER, "SHOWER", 0xf2cc},
    {ICON_FA_SHUTTLE_VAN, "SHUTTLE_VAN", 0xf5b6},
    {ICON_FA_SIGN, "SIGN", 0xf4d9},
    {ICON_FA_SIGN_IN_ALT, "SIGN_IN_ALT", 0xf2f6},
    {ICON_FA_SIGN_LANGUAGE, "SIGN_LANGUAGE", 0xf2a7},
    {ICON_FA_SIGN_OUT_ALT, "SIGN_OUT_ALT", 0xf2f5},
    {ICON_FA_SIGNAL, "SIGNAL", 0xf012},
    {ICON_FA_SIGNATURE, "SIGNATURE", 0xf5b7},
    {ICON_FA_SIM_CARD, "SIM_CARD", 0xf7c4},
    {ICON_FA_SINK, "SINK", 0xe06d},
    {ICON_FA_SITEMAP, "SITEMAP", 0xf0e8},
    {ICON_FA_SKATING, "SKATING", 0xf7c5},
    {ICON_FA_SKIING, "SKIING", 0xf7c9},
    {ICON_FA_SKIING_NORDIC, "SKIING_NORDIC", 0xf7ca},
    {ICON_FA_SKULL, "SKULL", 0xf54c},
    {ICON_FA_SKULL_CROSSBONES, "SKULL_CROSSBONES", 0xf714},
    {ICON_FA_SLASH, "SLASH", 0xf715},
    {ICON_FA_SLEIGH, "SLEIGH", 0xf7cc},
    {ICON_FA_SLIDERS_H, "SLIDERS_H", 0xf1de},
    {ICON_FA_SMILE, "SMILE", 0xf118},
    {ICON_FA_SMILE_BEAM, "SMILE_BEAM", 0xf5b8},
    {ICON_FA_SMILE_WINK, "SMILE_WINK", 0xf4da},
    {ICON_FA_SMOG, "SMOG", 0xf75f},
    {ICON_FA_SMOKING, "SMOKING", 0xf48d},
    {ICON_FA_SMOKING_BAN, "SMOKING_BAN", 0xf54d},
    {ICON_FA_SMS, "SMS", 0xf7cd},
    {ICON_FA_SNOWBOARDING, "SNOWBOARDING", 0xf7ce},
    {ICON_FA_SNOWFLAKE, "SNOWFLAKE", 0xf2dc},
    {ICON_FA_SNOWMAN, "SNOWMAN", 0xf7d0},
    {ICON_FA_SNOWPLOW, "SNOWPLOW", 0xf7d2},
    {ICON_FA_SOAP, "SOAP", 0xe06e},
    {ICON_FA_SOCKS, "SOCKS", 0xf696},
    {ICON_FA_SOLAR_PANEL, "SOLAR_PANEL", 0xf5ba},
    {ICON_FA_SORT, "SORT", 0xf0dc},
    {ICON_FA_SORT_ALPHA_DOWN, "SORT_ALPHA_DOWN", 0xf15d},
    {ICON_FA_SORT_ALPHA_DOWN_ALT, "SORT_ALPHA_DOWN_ALT", 0xf881},
    {ICON_FA_SORT_ALPHA_UP, "SORT_ALPHA_UP", 0xf15e},
    {ICON_FA_SORT_ALPHA_UP_ALT, "SORT_ALPHA_UP_ALT", 0xf882},
    {ICON_FA_SORT_AMOUNT_DOWN, "SORT_AMOUNT_DOWN", 0xf160},
    {ICON_FA_SORT_AMOUNT_DOWN_ALT, "SORT_AMOUNT_DOWN_ALT", 0xf884},
    {ICON_FA_SORT_AMOUNT_UP, "SORT_AMOUNT_UP", 0xf161},
    {ICON_FA_SORT_AMOUNT_UP_ALT, "SORT_AMOUNT_UP_ALT", 0xf885},
    {ICON_FA_SORT_DOWN, "SORT_DOWN", 0xf0dd},
    {ICON_FA_SORT_NUMERIC_DOWN, "SORT_NUMERIC_DOWN", 0xf162},
    {ICON_FA_SORT_NUMERIC_DOWN_ALT, "SORT_NUMERIC_DOWN_ALT", 0xf886},
    {ICON_FA_SORT_NUMERIC_UP, "SORT_NUMERIC_UP", 0xf163},
    {ICON_FA_SORT_NUMERIC_UP_ALT, "SORT_NUMERIC_UP_ALT", 0xf887},
    {ICON_FA_SORT_UP, "SORT_UP", 0xf0de},
    {ICON_FA_SPA, "SPA", 0xf5bb},
    {ICON_FA_SPACE_SHUTTLE, "SPACE_SHUTTLE", 0xf197},
    {ICON_FA_SPELL_CHECK, "SPELL_CHECK", 0xf891},
    {ICON_FA_SPIDER, "SPIDER", 0xf717},
    {ICON_FA_SPINNER, "SPINNER", 0xf110},
    {ICON_FA_SPLOTCH, "SPLOTCH", 0xf5bc},
    {ICON_FA_SPRAY_CAN, "SPRAY_CAN", 0xf5bd},
    {ICON_FA_SQUARE, "SQUARE", 0xf0c8},
    {ICON_FA_SQUARE_FULL, "SQUARE_FULL", 0xf45c},
    {ICON_FA_SQUARE_ROOT_ALT, "SQUARE_ROOT_ALT", 0xf698},
    {ICON_FA_STAMP, "STAMP", 0xf5bf},
    {ICON_FA_STAR, "STAR", 0xf005},
    {ICON_FA_STAR_AND_CRESCENT, "STAR_AND_CRESCENT", 0xf699},
    {ICON_FA_STAR_HALF, "STAR_HALF", 0xf089},
    {ICON_FA_STAR_HALF_ALT, "STAR_HALF_ALT", 0xf5c0},
    {ICON_FA_STAR_OF_DAVID, "STAR_OF_DAVID", 0xf69a},
    {ICON_FA_STAR_OF_LIFE, "STAR_OF_LIFE", 0xf621},
    {ICON_FA_STEP_BACKWARD, "STEP_BACKWARD", 0xf048},
    {ICON_FA_STEP_FORWARD, "STEP_FORWARD", 0xf051},
    {ICON_FA_STETHOSCOPE, "STETHOSCOPE", 0xf0f1},
    {ICON_FA_STICKY_NOTE, "STICKY_NOTE", 0xf249},
    {ICON_FA_STOP, "STOP", 0xf04d},
    {ICON_FA_STOP_CIRCLE, "STOP_CIRCLE", 0xf28d},
    {ICON_FA_STOPWATCH, "STOPWATCH", 0xf2f2},
    {ICON_FA_STOPWATCH_20, "STOPWATCH_20", 0xe06f},
    {ICON_FA_STORE, "STORE", 0xf54e},
    {ICON_FA_STORE_ALT, "STORE_ALT", 0xf54f},
    {ICON_FA_STORE_ALT_SLASH, "STORE_ALT_SLASH", 0xe070},
    {ICON_FA_STORE_SLASH, "STORE_SLASH", 0xe071},
    {ICON_FA_STREAM, "STREAM", 0xf550},
    {ICON_FA_STREET_VIEW, "STREET_VIEW", 0xf21d},
    {ICON_FA_STRIKETHROUGH, "STRIKETHROUGH", 0xf0cc},
    {ICON_FA_STROOPWAFEL, "STROOPWAFEL", 0xf551},
    {ICON_FA_SUBSCRIPT, "SUBSCRIPT", 0xf12c},
    {ICON_FA_SUBWAY, "SUBWAY", 0xf239},
    {ICON_FA_SUITCASE, "SUITCASE", 0xf0f2},
    {ICON_FA_SUITCASE_ROLLING, "SUITCASE_ROLLING", 0xf5c1},
    {ICON_FA_SUN, "SUN", 0xf185},
    {ICON_FA_SUPERSCRIPT, "SUPERSCRIPT", 0xf12b},
    {ICON_FA_SURPRISE, "SURPRISE", 0xf5c2},
    {ICON_FA_SWATCHBOOK, "SWATCHBOOK", 0xf5c3},
    {ICON_FA_SWIMMER, "SWIMMER", 0xf5c4},
    {ICON_FA_SWIMMING_POOL, "SWIMMING_POOL", 0xf5c5},
    {ICON_FA_SYNAGOGUE, "SYNAGOGUE", 0xf69b},
    {ICON_FA_SYNC, "SYNC", 0xf021},
    {ICON_FA_SYNC_ALT, "SYNC_ALT", 0xf2f1},
    {ICON_FA_SYRINGE, "SYRINGE", 0xf48e},
    {ICON_FA_TABLE, "TABLE", 0xf0ce},
    {ICON_FA_TABLE_TENNIS, "TABLE_TENNIS", 0xf45d},
    {ICON_FA_TABLET, "TABLET", 0xf10a},
    {ICON_FA_TABLET_ALT, "TABLET_ALT", 0xf3fa},
    {ICON_FA_TABLETS, "TABLETS", 0xf490},
    {ICON_FA_TACHOMETER_ALT, "TACHOMETER_ALT", 0xf3fd},
    {ICON_FA_TAG, "TAG", 0xf02b},
    {ICON_FA_TAGS, "TAGS", 0xf02c},
    {ICON_FA_TAPE, "TAPE", 0xf4db},
    {ICON_FA_TASKS, "TASKS", 0xf0ae},
    {ICON_FA_TAXI, "TAXI", 0xf1ba},
    {ICON_FA_TEETH, "TEETH", 0xf62e},
    {ICON_FA_TEETH_OPEN, "TEETH_OPEN", 0xf62f},
    {ICON_FA_TEMPERATURE_HIGH, "TEMPERATURE_HIGH", 0xf769},
    {ICON_FA_TEMPERATURE_LOW, "TEMPERATURE_LOW", 0xf76b},
    {ICON_FA_TENGE, "TENGE", 0xf7d7},
    {ICON_FA_TERMINAL, "TERMINAL", 0xf120},
    {ICON_FA_TEXT_HEIGHT, "TEXT_HEIGHT", 0xf034},
    {ICON_FA_TEXT_WIDTH, "TEXT_WIDTH", 0xf035},
    {ICON_FA_TH, "TH", 0xf00a},
    {ICON_FA_TH_LARGE, "TH_LARGE", 0xf009},
    {ICON_FA_TH_LIST, "TH_LIST", 0xf00b},
    {ICON_FA_THEATER_MASKS, "THEATER_MASKS", 0xf630},
    {ICON_FA_THERMOMETER, "THERMOMETER", 0xf491},
    {ICON_FA_THERMOMETER_EMPTY, "THERMOMETER_EMPTY", 0xf2cb},
    {ICON_FA_THERMOMETER_FULL, "THERMOMETER_FULL", 0xf2c7},
    {ICON_FA_THERMOMETER_HALF, "THERMOMETER_HALF", 0xf2c9},
    {ICON_FA_THERMOMETER_QUARTER, "THERMOMETER_QUARTER", 0xf2ca},
    {ICON_FA_THERMOMETER_THREE_QUARTERS, "THERMOMETER_THREE_QUARTERS", 0xf2c8},
    {ICON_FA_THUMBS_DOWN, "THUMBS_DOWN", 0xf165},
    {ICON_FA_THUMBS_UP, "THUMBS_UP", 0xf164},
    {ICON_FA_THUMBTACK, "THUMBTACK", 0xf08d},
    {ICON_FA_TICKET_ALT, "TICKET_ALT", 0xf3ff},
    {ICON_FA_TIMES, "TIMES", 0xf00d},
    {ICON_FA_TIMES_CIRCLE, "TIMES_CIRCLE", 0xf057},
    {ICON_FA_TINT, "TINT", 0xf043},
    {ICON_FA_TINT_SLASH, "TINT_SLASH", 0xf5c7},
    {ICON_FA_TIRED, "TIRED", 0xf5c8},
    {ICON_FA_TOGGLE_OFF, "TOGGLE_OFF", 0xf204},
    {ICON_FA_TOGGLE_ON, "TOGGLE_ON", 0xf205},
    {ICON_FA_TOILET, "TOILET", 0xf7d8},
    {ICON_FA_TOILET_PAPER, "TOILET_PAPER", 0xf71e},
    {ICON_FA_TOILET_PAPER_SLASH, "TOILET_PAPER_SLASH", 0xe072},
    {ICON_FA_TOOLBOX, "TOOLBOX", 0xf552},
    {ICON_FA_TOOLS, "TOOLS", 0xf7d9},
    {ICON_FA_TOOTH, "TOOTH", 0xf5c9},
    {ICON_FA_TORAH, "TORAH", 0xf6a0},
    {ICON_FA_TORII_GATE, "TORII_GATE", 0xf6a1},
    {ICON_FA_TRACTOR, "TRACTOR", 0xf722},
    {ICON_FA_TRADEMARK, "TRADEMARK", 0xf25c},
    {ICON_FA_TRAFFIC_LIGHT, "TRAFFIC_LIGHT", 0xf637},
    {ICON_FA_TRAILER, "TRAILER", 0xe041},
    {ICON_FA_TRAIN, "TRAIN", 0xf238},
    {ICON_FA_TRAM, "TRAM", 0xf7da},
    {ICON_FA_TRANSGENDER, "TRANSGENDER", 0xf224},
    {ICON_FA_TRANSGENDER_ALT, "TRANSGENDER_ALT", 0xf225},
    {ICON_FA_TRASH, "TRASH", 0xf1f8},
    {ICON_FA_TRASH_ALT, "TRASH_ALT", 0xf2ed},
    {ICON_FA_TRASH_RESTORE, "TRASH_RESTORE", 0xf829},
    {ICON_FA_TRASH_RESTORE_ALT, "TRASH_RESTORE_ALT", 0xf82a},
    {ICON_FA_TREE, "TREE", 0xf1bb},
    {ICON_FA_TROPHY, "TROPHY", 0xf091},
    {ICON_FA_TRUCK, "TRUCK", 0xf0d1},
    {ICON_FA_TRUCK_LOADING, "TRUCK_LOADING", 0xf4de},
    {ICON_FA_TRUCK_MONSTER, "TRUCK_MONSTER", 0xf63b},
    {ICON_FA_TRUCK_MOVING, "TRUCK_MOVING", 0xf4df},
    {ICON_FA_TRUCK_PICKUP, "TRUCK_PICKUP", 0xf63c},
    {ICON_FA_TSHIRT, "TSHIRT", 0xf553},
    {ICON_FA_TTY, "TTY", 0xf1e4},
    {ICON_FA_TV, "TV", 0xf26c},
    {ICON_FA_UMBRELLA, "UMBRELLA", 0xf0e9},
    {ICON_FA_UMBRELLA_BEACH, "UMBRELLA_BEACH", 0xf5ca},
    {ICON_FA_UNDERLINE, "UNDERLINE", 0xf0cd},
    {ICON_FA_UNDO, "UNDO", 0xf0e2},
    {ICON_FA_UNDO_ALT, "UNDO_ALT", 0xf2ea},
    {ICON_FA_UNIVERSAL_ACCESS, "UNIVERSAL_ACCESS", 0xf29a},
    {ICON_FA_UNIVERSITY, "UNIVERSITY", 0xf19c},
    {ICON_FA_UNLINK, "UNLINK", 0xf127},
    {ICON_FA_UNLOCK, "UNLOCK", 0xf09c},
    {ICON_FA_UNLOCK_ALT, "UNLOCK_ALT", 0xf13e},
    {ICON_FA_UPLOAD, "UPLOAD", 0xf093},
    {ICON_FA_USER, "USER", 0xf007},
    {ICON_FA_USER_ALT, "USER_ALT", 0xf406},
    {ICON_FA_USER_ALT_SLASH, "USER_ALT_SLASH", 0xf4fa},
    {ICON_FA_USER_ASTRONAUT, "USER_ASTRONAUT", 0xf4fb},
    {ICON_FA_USER_CHECK, "USER_CHECK", 0xf4fc},
    {ICON_FA_USER_CIRCLE, "USER_CIRCLE", 0xf2bd},
    {ICON_FA_USER_CLOCK, "USER_CLOCK", 0xf4fd},
    {ICON_FA_USER_COG, "USER_COG", 0xf4fe},
    {ICON_FA_USER_EDIT, "USER_EDIT", 0xf4ff},
    {ICON_FA_USER_FRIENDS, "USER_FRIENDS", 0xf500},
    {ICON_FA_USER_GRADUATE, "USER_GRADUATE", 0xf501},
    {ICON_FA_USER_INJURED, "USER_INJURED", 0xf728},
    {ICON_FA_USER_LOCK, "USER_LOCK", 0xf502},
    {ICON_FA_USER_MD, "USER_MD", 0xf0f0},
    {ICON_FA_USER_MINUS, "USER_MINUS", 0xf503},
    {ICON_FA_USER_NINJA, "USER_NINJA", 0xf504},
    {ICON_FA_USER_NURSE, "USER_NURSE", 0xf82f},
    {ICON_FA_USER_PLUS, "USER_PLUS", 0xf234},
    {ICON_FA_USER_SECRET, "USER_SECRET", 0xf21b},
    {ICON_FA_USER_SHIELD, "USER_SHIELD", 0xf505},
    {ICON_FA_USER_SLASH, "USER_SLASH", 0xf506},
    {ICON_FA_USER_TAG, "USER_TAG", 0xf507},
    {ICON_FA_USER_TIE, "USER_TIE", 0xf508},
    {ICON_FA_USER_TIMES, "USER_TIMES", 0xf235},
    {ICON_FA_USERS, "USERS", 0xf0c0},
    {ICON_FA_USERS_COG, "USERS_COG", 0xf509},
    {ICON_FA_USERS_SLASH, "USERS_SLASH", 0xe073},
    {ICON_FA_UTENSIL_SPOON, "UTENSIL_SPOON", 0xf2e5},
    {ICON_FA_UTENSILS, "UTENSILS", 0xf2e7},
    {ICON_FA_VECTOR_SQUARE, "VECTOR_SQUARE", 0xf5cb},
    {ICON_FA_VENUS, "VENUS", 0xf221},
    {ICON_FA_VENUS_DOUBLE, "VENUS_DOUBLE", 0xf226},
    {ICON_FA_VENUS_MARS, "VENUS_MARS", 0xf228},
    {ICON_FA_VEST, "VEST", 0xe085},
    {ICON_FA_VEST_PATCHES, "VEST_PATCHES", 0xe086},
    {ICON_FA_VIAL, "VIAL", 0xf492},
    {ICON_FA_VIALS, "VIALS", 0xf493},
    {ICON_FA_VIDEO, "VIDEO", 0xf03d},
    {ICON_FA_VIDEO_SLASH, "VIDEO_SLASH", 0xf4e2},
    {ICON_FA_VIHARA, "VIHARA", 0xf6a7},
    {ICON_FA_VIRUS, "VIRUS", 0xe074},
    {ICON_FA_VIRUS_SLASH, "VIRUS_SLASH", 0xe075},
    {ICON_FA_VIRUSES, "VIRUSES", 0xe076},
    {ICON_FA_VOICEMAIL, "VOICEMAIL", 0xf897},
    {ICON_FA_VOLLEYBALL_BALL, "VOLLEYBALL_BALL", 0xf45f},
    {ICON_FA_VOLUME_DOWN, "VOLUME_DOWN", 0xf027},
    {ICON_FA_VOLUME_MUTE, "VOLUME_MUTE", 0xf6a9},
    {ICON_FA_VOLUME_OFF, "VOLUME_OFF", 0xf026},
    {ICON_FA_VOLUME_UP, "VOLUME_UP", 0xf028},
    {ICON_FA_VOTE_YEA, "VOTE_YEA", 0xf772},
    {ICON_FA_VR_CARDBOARD, "VR_CARDBOARD", 0xf729},
    {ICON_FA_WALKING, "WALKING", 0xf554},
    {ICON_FA_WALLET, "WALLET", 0xf555},
    {ICON_FA_WAREHOUSE, "WAREHOUSE", 0xf494},
    {ICON_FA_WATER, "WATER", 0xf773},
    {ICON_FA_WAVE_SQUARE, "WAVE_SQUARE", 0xf83e},
    {ICON_FA_WEIGHT, "WEIGHT", 0xf496},
    {ICON_FA_WEIGHT_HANGING, "WEIGHT_HANGING", 0xf5cd},
    {ICON_FA_WHEELCHAIR, "WHEELCHAIR", 0xf193},
    {ICON_FA_WIFI, "WIFI", 0xf1eb},
    {ICON_FA_WIND, "WIND", 0xf72e},
    {ICON_FA_WINDOW_CLOSE, "WINDOW_CLOSE", 0xf410},
    {ICON_FA_WINDOW_MAXIMIZE, "WINDOW_MAXIMIZE", 0xf2d0},
    {ICON_FA_WINDOW_MINIMIZE, "WINDOW_MINIMIZE", 0xf2d1},
    {ICON_FA_WINDOW_RESTORE, "WINDOW_RESTORE", 0xf2d2},
    {ICON_FA_WINE_BOTTLE, "WINE_BOTTLE", 0xf72f},
    {ICON_FA_WINE_GLASS, "WINE_GLASS", 0xf4e3},
    {ICON_FA_WINE_GLASS_ALT, "WINE_GLASS_ALT", 0xf5ce},
    {ICON_FA_WON_SIGN, "WON_SIGN", 0xf159},
    {ICON_FA_WRENCH, "WRENCH", 0xf0ad},
    {ICON_FA_X_RAY, "X_RAY", 0xf497},
    {ICON_FA_YEN_SIGN, "YEN_SIGN", 0xf157},
    {ICON_FA_YIN_YANG, "YIN_YANG", 0xf6ad}

    #pragma endregion
};

constexpr size_t FA5_ICONS_COUNT = sizeof(FA5_ICONS) / sizeof(FontAwesome5Icon);